// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _17: (x0,x1) => x0.get(x1),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _754: x0 => x0.baseURI,
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _919: x0 => x0.headers,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1283: (x0,x1) => x0.createElement(x1),
      _1284: (x0,x1) => x0.querySelector(x1),
      _1285: (x0,x1) => x0.appendChild(x1),
      _1286: x0 => ({type: x0}),
      _1287: (x0,x1) => new Blob(x0,x1),
      _1288: x0 => globalThis.URL.createObjectURL(x0),
      _1290: (x0,x1,x2,x3) => x0.sendCommand(x1,x2,x3),
      _1291: () => globalThis.PdfiumWasmCommunicator,
      _1293: x0 => { globalThis.pdfiumWasmWorkerUrl = x0 },
      _1294: (x0,x1) => x0.writeText(x1),
      _1295: x0 => x0.preventDefault(),
      _1296: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1296(f,arguments.length,x0) }),
      _1297: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1298: x0 => x0.createRange(),
      _1299: (x0,x1) => x0.selectNode(x1),
      _1300: x0 => x0.getSelection(),
      _1301: x0 => x0.removeAllRanges(),
      _1302: (x0,x1) => x0.addRange(x1),
      _1303: (x0,x1) => x0.createElement(x1),
      _1304: (x0,x1) => x0.append(x1),
      _1305: (x0,x1,x2) => x0.insertRule(x1,x2),
      _1306: (x0,x1) => x0.add(x1),
      _1307: x0 => x0.preventDefault(),
      _1308: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1308(f,arguments.length,x0) }),
      _1309: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1310: () => globalThis.window.navigator.userAgent,
      _1311: x0 => globalThis.URL.revokeObjectURL(x0),
      _1312: x0 => x0.remove(),
      _1314: (x0,x1,x2,x3,x4,x5) => x0.drawImage(x1,x2,x3,x4,x5),
      _1317: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1317(f,arguments.length,x0) }),
      _1318: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1318(f,arguments.length,x0) }),
      _1319: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1319(f,arguments.length,x0) }),
      _1320: (x0,x1) => x0.append(x1),
      _1321: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1322: (x0,x1) => x0.replaceChildren(x1),
      _1323: x0 => x0.click(),
      _1324: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24) => ({aspectRatio: x0,background: x1,center: x2,checkCrossOrigin: x3,checkOrientation: x4,cropBoxMovable: x5,cropBoxResizable: x6,dragMode: x7,guides: x8,highlight: x9,initialAspectRatio: x10,minContainerHeight: x11,minContainerWidth: x12,minCropBoxHeight: x13,minCropBoxWidth: x14,modal: x15,movable: x16,rotatable: x17,scalable: x18,toggleDragModeOnDblclick: x19,viewMode: x20,wheelZoomRatio: x21,zoomOnTouch: x22,zoomOnWheel: x23,zoomable: x24}),
      _1325: (x0,x1) => new Cropper(x0,x1),
      _1326: () => ({}),
      _1327: (x0,x1) => x0.getCroppedCanvas(x1),
      _1328: x0 => x0.getCroppedCanvas(),
      _1329: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1329(f,arguments.length,x0) }),
      _1330: (x0,x1,x2) => x0.toBlob(x1,x2),
      _1331: (x0,x1) => x0.rotate(x1),
      _1332: (x0,x1) => x0.scale(x1),
      _1333: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1334: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1336: (x0,x1) => x0.getAttribute(x1),
      _1340: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1342: (x0,x1) => x0.canShare(x1),
      _1343: (x0,x1) => x0.share(x1),
      _1344: (x0,x1) => ({title: x0,text: x1}),
      _1345: x0 => ({text: x0}),
      _1361: (x0,x1) => x0.item(x1),
      _1362: x0 => x0.decode(),
      _1363: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1364: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1365: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1365(f,arguments.length,x0) }),
      _1366: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1366(f,arguments.length,x0) }),
      _1367: x0 => x0.send(),
      _1368: () => new XMLHttpRequest(),
      _1378: (x0,x1) => x0.item(x1),
      _1379: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1379(f,arguments.length,x0) }),
      _1380: (x0,x1) => x0.getItem(x1),
      _1381: (x0,x1) => x0.removeItem(x1),
      _1382: (x0,x1,x2) => x0.setItem(x1,x2),
      _1397: (x0,x1) => x0.getContext(x1),
      _1398: (x0,x1,x2,x3,x4) => x0.clearRect(x1,x2,x3,x4),
      _1399: x0 => x0.close(),
      _1400: () => new FileReader(),
      _1402: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1403: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1403(f,arguments.length,x0) }),
      _1404: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1405: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1405(f,arguments.length,x0) }),
      _1406: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1406(f,arguments.length,x0) }),
      _1407: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1407(f,arguments.length,x0) }),
      _1408: (x0,x1) => x0.removeChild(x1),
      _1409: x0 => new Blob(x0),
      _1411: x0 => x0.deviceMemory,
      _1412: () => new SpeechSynthesisUtterance(),
      _1413: x0 => x0.pause(),
      _1414: x0 => x0.resume(),
      _1415: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1415(f,arguments.length,x0) }),
      _1416: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1416(f,arguments.length,x0) }),
      _1417: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1417(f,arguments.length,x0) }),
      _1418: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1418(f,arguments.length,x0) }),
      _1419: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1419(f,arguments.length,x0) }),
      _1420: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1420(f,arguments.length,x0) }),
      _1421: (x0,x1) => x0.speak(x1),
      _1422: x0 => x0.cancel(),
      _1423: x0 => x0.getVoices(),
      _1424: () => globalThis.Intl.DateTimeFormat(),
      _1425: x0 => x0.resolvedOptions(),
      _1426: () => globalThis.Intl.supportedValuesOf,
      _1428: x0 => x0.timeZone,
      _1429: (x0,x1) => x0.key(x1),
      _1430: (x0,x1,x2,x3,x4,x5,x6,x7) => x0.unwrapKey(x1,x2,x3,x4,x5,x6,x7),
      _1431: (x0,x1,x2,x3,x4,x5) => x0.importKey(x1,x2,x3,x4,x5),
      _1432: (x0,x1,x2,x3) => x0.generateKey(x1,x2,x3),
      _1433: (x0,x1,x2,x3,x4) => x0.wrapKey(x1,x2,x3,x4),
      _1434: (x0,x1,x2) => x0.exportKey(x1,x2),
      _1435: (x0,x1) => x0.getRandomValues(x1),
      _1436: (x0,x1,x2,x3) => x0.encrypt(x1,x2,x3),
      _1437: (x0,x1,x2,x3) => x0.decrypt(x1,x2,x3),
      _1444: Date.now,
      _1446: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1447: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1448: () => new Error().stack,
      _1449: () => typeof dartUseDateNowForTicks !== "undefined",
      _1450: () => 1000 * performance.now(),
      _1451: () => Date.now(),
      _1452: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1453: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1454: () => new WeakMap(),
      _1455: (map, o) => map.get(o),
      _1456: (map, o, v) => map.set(o, v),
      _1457: (exn) => exn.toString(),
      _1458: (exn) => exn.stack,
      _1459: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1460: x0 => new WeakRef(x0),
      _1461: x0 => x0.deref(),
      _1462: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1462(f,arguments.length,x0) }),
      _1463: x0 => new FinalizationRegistry(x0),
      _1464: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _1466: (x0,x1) => x0.unregister(x1),
      _1468: () => globalThis.WeakRef,
      _1469: () => globalThis.FinalizationRegistry,
      _1471: x0 => x0.call(),
      _1472: s => JSON.stringify(s),
      _1473: s => printToConsole(s),
      _1474: (o, p, r) => o.replaceAll(p, () => r),
      _1475: (o, p, r) => o.replace(p, () => r),
      _1476: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1477: s => s.toUpperCase(),
      _1478: s => s.trim(),
      _1479: s => s.trimLeft(),
      _1480: s => s.trimRight(),
      _1481: (string, times) => string.repeat(times),
      _1482: Function.prototype.call.bind(String.prototype.indexOf),
      _1483: (s, p, i) => s.lastIndexOf(p, i),
      _1484: (string, token) => string.split(token),
      _1485: Object.is,
      _1488: (o, t) => typeof o === t,
      _1489: (o, c) => o instanceof c,
      _1490: o => Object.keys(o),
      _1493: (o, a) => o + a,
      _1503: (o, a) => o == a,
      _1520: x0 => new Array(x0),
      _1522: x0 => x0.length,
      _1524: (x0,x1) => x0[x1],
      _1525: (x0,x1,x2) => { x0[x1] = x2 },
      _1528: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1530: x0 => new Int8Array(x0),
      _1531: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1533: x0 => new Uint8ClampedArray(x0),
      _1535: x0 => new Int16Array(x0),
      _1537: x0 => new Uint16Array(x0),
      _1539: x0 => new Int32Array(x0),
      _1541: x0 => new Uint32Array(x0),
      _1543: x0 => new Float32Array(x0),
      _1545: x0 => new Float64Array(x0),
      _1566: (x0,x1) => x0.call(x1),
      _1569: x0 => x0.random(),
      _1570: (x0,x1) => x0.getRandomValues(x1),
      _1571: () => globalThis.crypto,
      _1572: () => globalThis.Math,
      _1574: () => globalThis.performance,
      _1575: () => globalThis.JSON,
      _1576: x0 => x0.measure,
      _1577: x0 => x0.mark,
      _1578: x0 => x0.clearMeasures,
      _1579: x0 => x0.clearMarks,
      _1580: (x0,x1,x2,x3) => x0.measure(x1,x2,x3),
      _1581: (x0,x1,x2) => x0.mark(x1,x2),
      _1582: x0 => x0.clearMeasures(),
      _1583: x0 => x0.clearMarks(),
      _1584: (x0,x1) => x0.parse(x1),
      _1585: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1586: (handle) => clearTimeout(handle),
      _1587: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1588: (handle) => clearInterval(handle),
      _1589: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1590: () => Date.now(),
      _1591: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1592: (x0,x1) => x0.exec(x1),
      _1593: (x0,x1) => x0.test(x1),
      _1594: x0 => x0.pop(),
      _1596: o => o === undefined,
      _1598: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1600: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1601: o => o instanceof RegExp,
      _1602: (l, r) => l === r,
      _1603: o => o,
      _1604: o => o,
      _1605: o => o,
      _1606: b => !!b,
      _1607: o => o.length,
      _1609: (o, i) => o[i],
      _1610: f => f.dartFunction,
      _1611: () => ({}),
      _1612: () => [],
      _1614: () => globalThis,
      _1615: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1616: (o, p) => p in o,
      _1617: (o, p) => o[p],
      _1618: (o, p, v) => o[p] = v,
      _1619: (o, m, a) => o[m].apply(o, a),
      _1621: o => String(o),
      _1622: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1623: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1623(f,arguments.length,x0) }),
      _1624: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1624(f,arguments.length,x0,x1) }),
      _1625: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1626: o => [o],
      _1627: (o0, o1) => [o0, o1],
      _1628: (o0, o1, o2) => [o0, o1, o2],
      _1629: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1630: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1631: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1632: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1633: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1634: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1635: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1636: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1637: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1638: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1639: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1640: x0 => new ArrayBuffer(x0),
      _1641: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1642: x0 => x0.input,
      _1643: x0 => x0.index,
      _1644: x0 => x0.groups,
      _1645: x0 => x0.flags,
      _1646: x0 => x0.multiline,
      _1647: x0 => x0.ignoreCase,
      _1648: x0 => x0.unicode,
      _1649: x0 => x0.dotAll,
      _1650: (x0,x1) => { x0.lastIndex = x1 },
      _1651: (o, p) => p in o,
      _1652: (o, p) => o[p],
      _1653: (o, p, v) => o[p] = v,
      _1655: x0 => x0.exports,
      _1656: (x0,x1) => globalThis.WebAssembly.instantiateStreaming(x0,x1),
      _1657: x0 => x0.instance,
      _1659: x0 => new WebAssembly.Memory(x0),
      _1660: x0 => x0.buffer,
      _1663: x0 => x0.arrayBuffer(),
      _1665: x0 => x0.sqlite3_initialize,
      _1667: (x0,x1,x2,x3,x4) => x0.sqlite3_open_v2(x1,x2,x3,x4),
      _1668: (x0,x1) => x0.sqlite3_close_v2(x1),
      _1669: (x0,x1,x2) => x0.sqlite3_extended_result_codes(x1,x2),
      _1670: (x0,x1) => x0.sqlite3_extended_errcode(x1),
      _1671: (x0,x1) => x0.sqlite3_errmsg(x1),
      _1672: (x0,x1) => x0.sqlite3_errstr(x1),
      _1673: x0 => x0.sqlite3_error_offset,
      _1677: (x0,x1) => x0.sqlite3_last_insert_rowid(x1),
      _1678: (x0,x1) => x0.sqlite3_changes(x1),
      _1679: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_exec(x1,x2,x3,x4,x5),
      _1682: (x0,x1,x2,x3,x4,x5,x6) => x0.sqlite3_prepare_v3(x1,x2,x3,x4,x5,x6),
      _1683: (x0,x1) => x0.sqlite3_finalize(x1),
      _1684: (x0,x1) => x0.sqlite3_step(x1),
      _1685: (x0,x1) => x0.sqlite3_reset(x1),
      _1686: (x0,x1) => x0.sqlite3_stmt_isexplain(x1),
      _1688: (x0,x1) => x0.sqlite3_column_count(x1),
      _1689: (x0,x1) => x0.sqlite3_bind_parameter_count(x1),
      _1691: (x0,x1,x2) => x0.sqlite3_column_name(x1,x2),
      _1692: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_bind_blob64(x1,x2,x3,x4,x5),
      _1693: (x0,x1,x2,x3) => x0.sqlite3_bind_double(x1,x2,x3),
      _1694: (x0,x1,x2,x3) => x0.sqlite3_bind_int64(x1,x2,x3),
      _1695: (x0,x1,x2) => x0.sqlite3_bind_null(x1,x2),
      _1696: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_bind_text(x1,x2,x3,x4,x5),
      _1697: (x0,x1,x2) => x0.sqlite3_column_blob(x1,x2),
      _1698: (x0,x1,x2) => x0.sqlite3_column_double(x1,x2),
      _1699: (x0,x1,x2) => x0.sqlite3_column_int64(x1,x2),
      _1700: (x0,x1,x2) => x0.sqlite3_column_text(x1,x2),
      _1701: (x0,x1,x2) => x0.sqlite3_column_bytes(x1,x2),
      _1702: (x0,x1,x2) => x0.sqlite3_column_type(x1,x2),
      _1703: (x0,x1) => x0.sqlite3_value_blob(x1),
      _1704: (x0,x1) => x0.sqlite3_value_double(x1),
      _1705: (x0,x1) => x0.sqlite3_value_type(x1),
      _1706: (x0,x1) => x0.sqlite3_value_int64(x1),
      _1707: (x0,x1) => x0.sqlite3_value_text(x1),
      _1708: (x0,x1) => x0.sqlite3_value_bytes(x1),
      _1711: (x0,x1) => x0.sqlite3_user_data(x1),
      _1712: (x0,x1,x2,x3,x4) => x0.sqlite3_result_blob64(x1,x2,x3,x4),
      _1713: (x0,x1,x2) => x0.sqlite3_result_double(x1,x2),
      _1714: (x0,x1,x2,x3) => x0.sqlite3_result_error(x1,x2,x3),
      _1715: (x0,x1,x2) => x0.sqlite3_result_int64(x1,x2),
      _1716: (x0,x1) => x0.sqlite3_result_null(x1),
      _1717: (x0,x1,x2,x3,x4) => x0.sqlite3_result_text(x1,x2,x3,x4),
      _1718: x0 => x0.sqlite3_result_subtype,
      _1737: (x0,x1) => x0.dart_sqlite3_malloc(x1),
      _1738: (x0,x1) => x0.dart_sqlite3_free(x1),
      _1739: (x0,x1,x2,x3) => x0.dart_sqlite3_register_vfs(x1,x2,x3),
      _1740: (x0,x1,x2,x3,x4,x5) => x0.dart_sqlite3_create_scalar_function(x1,x2,x3,x4,x5),
      _1743: x0 => x0.dart_sqlite3_updates,
      _1744: x0 => x0.dart_sqlite3_commits,
      _1745: x0 => x0.dart_sqlite3_rollbacks,
      _1749: x0 => ({initial: x0}),
      _1750: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1750(f,arguments.length,x0) }),
      _1751: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1751(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1752: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1752(f,arguments.length,x0,x1,x2) }),
      _1753: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1753(f,arguments.length,x0,x1,x2,x3) }),
      _1754: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1754(f,arguments.length,x0,x1,x2,x3) }),
      _1755: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1755(f,arguments.length,x0,x1,x2) }),
      _1756: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1756(f,arguments.length,x0,x1) }),
      _1757: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1757(f,arguments.length,x0,x1) }),
      _1758: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1758(f,arguments.length,x0) }),
      _1759: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1759(f,arguments.length,x0) }),
      _1760: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1760(f,arguments.length,x0,x1,x2,x3) }),
      _1761: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1761(f,arguments.length,x0,x1,x2,x3) }),
      _1762: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1762(f,arguments.length,x0,x1) }),
      _1763: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1763(f,arguments.length,x0,x1) }),
      _1764: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1764(f,arguments.length,x0,x1) }),
      _1765: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1765(f,arguments.length,x0,x1) }),
      _1766: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1766(f,arguments.length,x0,x1) }),
      _1767: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1767(f,arguments.length,x0,x1) }),
      _1768: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1768(f,arguments.length,x0,x1,x2) }),
      _1769: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1769(f,arguments.length,x0,x1,x2) }),
      _1770: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1770(f,arguments.length,x0,x1,x2) }),
      _1771: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1771(f,arguments.length,x0) }),
      _1772: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1772(f,arguments.length,x0) }),
      _1773: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1773(f,arguments.length,x0) }),
      _1774: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1774(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1775: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1775(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1776: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1776(f,arguments.length,x0) }),
      _1777: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1777(f,arguments.length,x0) }),
      _1778: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1778(f,arguments.length,x0,x1) }),
      _1779: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1779(f,arguments.length,x0,x1) }),
      _1780: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1780(f,arguments.length,x0,x1,x2) }),
      _1782: (x0,x1,x2,x3) => x0.call(x1,x2,x3),
      _1787: x0 => new URL(x0),
      _1788: (x0,x1) => new URL(x0,x1),
      _1789: (x0,x1) => globalThis.fetch(x0,x1),
      _1790: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1791: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1793: (x0,x1) => ({i: x0,p: x1}),
      _1794: (x0,x1) => ({c: x0,r: x1}),
      _1795: x0 => x0.i,
      _1796: x0 => x0.p,
      _1797: x0 => x0.c,
      _1798: x0 => x0.r,
      _1799: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1799(f,arguments.length,x0) }),
      _1800: (x0,x1) => x0.postMessage(x1),
      _1801: x0 => x0.close(),
      _1803: x0 => new Worker(x0),
      _1805: x0 => x0.getDirectory(),
      _1806: x0 => ({create: x0}),
      _1807: (x0,x1,x2) => x0.getFileHandle(x1,x2),
      _1808: x0 => x0.createSyncAccessHandle(),
      _1809: x0 => x0.close(),
      _1812: x0 => x0.close(),
      _1815: (x0,x1,x2) => x0.open(x1,x2),
      _1821: x0 => x0.start(),
      _1822: x0 => x0.terminate(),
      _1823: (x0,x1) => new SharedWorker(x0,x1),
      _1824: () => new MessageChannel(),
      _1829: x0 => new SharedArrayBuffer(x0),
      _1830: x0 => ({at: x0}),
      _1831: x0 => x0.getSize(),
      _1832: (x0,x1) => x0.truncate(x1),
      _1833: x0 => x0.flush(),
      _1836: x0 => x0.synchronizationBuffer,
      _1837: x0 => x0.communicationBuffer,
      _1838: (x0,x1,x2,x3) => ({clientVersion: x0,root: x1,synchronizationBuffer: x2,communicationBuffer: x3}),
      _1839: (x0,x1) => globalThis.IDBKeyRange.bound(x0,x1),
      _1840: x0 => ({autoIncrement: x0}),
      _1841: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      _1842: x0 => ({unique: x0}),
      _1843: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      _1844: (x0,x1) => x0.createObjectStore(x1),
      _1845: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1845(f,arguments.length,x0) }),
      _1846: (x0,x1,x2) => x0.transaction(x1,x2),
      _1847: (x0,x1) => x0.objectStore(x1),
      _1849: (x0,x1) => x0.index(x1),
      _1850: x0 => x0.openKeyCursor(),
      _1851: (x0,x1) => x0.getKey(x1),
      _1852: (x0,x1) => ({name: x0,length: x1}),
      _1853: (x0,x1) => x0.put(x1),
      _1854: (x0,x1) => x0.get(x1),
      _1855: (x0,x1) => x0.openCursor(x1),
      _1856: x0 => globalThis.IDBKeyRange.only(x0),
      _1857: (x0,x1,x2) => x0.put(x1,x2),
      _1858: (x0,x1) => x0.update(x1),
      _1859: (x0,x1) => x0.delete(x1),
      _1860: x0 => x0.name,
      _1861: x0 => x0.length,
      _1864: x0 => x0.continue(),
      _1865: () => globalThis.indexedDB,
      _1866: () => globalThis.navigator,
      _1867: (x0,x1) => x0.read(x1),
      _1868: (x0,x1,x2) => x0.read(x1,x2),
      _1869: (x0,x1) => x0.write(x1),
      _1870: (x0,x1,x2) => x0.write(x1,x2),
      _1871: x0 => ({create: x0}),
      _1872: (x0,x1,x2) => x0.getDirectoryHandle(x1,x2),
      _1874: (x0,x1,x2) => globalThis.Atomics.wait(x0,x1,x2),
      _1876: (x0,x1,x2) => globalThis.Atomics.notify(x0,x1,x2),
      _1877: (x0,x1,x2) => globalThis.Atomics.store(x0,x1,x2),
      _1878: (x0,x1) => globalThis.Atomics.load(x0,x1),
      _1879: () => globalThis.Int32Array,
      _1881: () => globalThis.Uint8Array,
      _1883: () => globalThis.DataView,
      _1885: x0 => x0.byteLength,
      _1887: x0 => globalThis.BigInt(x0),
      _1888: x0 => globalThis.Number(x0),
      _1895: x0 => new BroadcastChannel(x0),
      _1896: x0 => globalThis.Array.isArray(x0),
      _1897: (x0,x1) => x0.postMessage(x1),
      _1899: (x0,x1) => ({kind: x0,table: x1}),
      _1900: x0 => x0.kind,
      _1901: x0 => x0.table,
      _1902: () => new XMLHttpRequest(),
      _1903: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1905: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1906: (x0,x1) => x0.send(x1),
      _1907: x0 => x0.send(),
      _1909: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1909(f,arguments.length,x0) }),
      _1910: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1910(f,arguments.length,x0) }),
      _1935: (x0,x1,x2) => x0.wire__crate__api__pdf__extractor__analyze_pdf_pages(x1,x2),
      _1971: (x0,x1,x2,x3) => x0.wire__crate__api__security__decrypt(x1,x2,x3),
      _1976: (x0,x1,x2,x3) => x0.wire__crate__api__security__derive_key(x1,x2,x3),
      _1981: (x0,x1,x2) => x0.wire__crate__api__embeddings__embeddings_init(x1,x2),
      _1983: (x0,x1,x2,x3) => x0.wire__crate__api__security__encrypt(x1,x2,x3),
      _1996: (x0,x1,x2) => x0.wire__crate__api__pdf__extractor__extract_document_spans(x1,x2),
      _2009: (x0,x1,x2) => x0.wire__crate__api__embeddings__generate_embedding(x1,x2),
      _2014: (x0,x1) => x0.wire__crate__api__security__generate_salt(x1),
      _2027: (x0,x1,x2) => x0.wire__crate__api__markdown__get_markdown_chunk_count(x1,x2),
      _2039: (x0,x1,x2) => x0.wire__crate__api__graph__graph_compute_depths(x1,x2),
      _2040: (x0,x1,x2,x3) => x0.wire__crate__api__graph__graph_create(x1,x2,x3),
      _2041: (x0,x1) => x0.wire__crate__api__graph__graph_destroy(x1),
      _2042: (x0,x1) => x0.wire__crate__api__graph__graph_get_edges(x1),
      _2043: (x0,x1) => x0.wire__crate__api__graph__graph_get_nodes(x1),
      _2045: (x0,x1,x2) => x0.wire__crate__api__graph__graph_simulate(x1,x2),
      _2046: (x0,x1) => x0.wire__crate__api__graph__graph_tick(x1),
      _2076: (x0,x1,x2,x3) => x0.wire__crate__api__markdown__parse_markdown_chunk(x1,x2,x3),
      _2077: (x0,x1,x2) => x0.wire__crate__api__markdown__parse_markdown_full(x1,x2),
      _2080: (x0,x1,x2) => x0.wire__crate__api__memory_import__parse_memory_anki(x1,x2),
      _2081: (x0,x1,x2) => x0.wire__crate__api__memory_import__parse_memory_json(x1,x2),
      _2082: (x0,x1,x2) => x0.wire__crate__api__memory_import__parse_memory_text(x1,x2),
      _2087: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_execute_command(x1,x2,x3),
      _2088: (x0,x1,x2) => x0.wire__crate__api__plugins__plugins_export_configs(x1,x2),
      _2089: (x0,x1,x2) => x0.wire__crate__api__plugins__plugins_get_config(x1,x2),
      _2090: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_import_configs(x1,x2,x3),
      _2091: (x0,x1,x2,x3,x4) => x0.wire__crate__api__plugins__plugins_init(x1,x2,x3,x4),
      _2092: (x0,x1) => x0.wire__crate__api__plugins__plugins_list(x1),
      _2093: (x0,x1) => x0.wire__crate__api__plugins__plugins_list_config_descriptors(x1),
      _2094: (x0,x1) => x0.wire__crate__api__plugins__plugins_load_configs_from_vault(x1),
      _2095: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_query_panel_data(x1,x2,x3),
      _2096: (x0,x1,x2) => x0.wire__crate__api__plugins__plugins_reindex(x1,x2),
      _2097: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_set_config(x1,x2,x3),
      _2098: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_set_enabled(x1,x2,x3),
      _2099: (x0,x1) => x0.wire__crate__api__plugins__plugins_sync_configs_to_vault(x1),
      _2101: (x0,x1,x2,x3) => x0.wire__crate__api__roadmap__process_roadmap_data(x1,x2,x3),
      _2143: (x0,x1,x2,x3,x4,x5) => x0.wire__crate__api__vector_store__types__vector_document_new(x1,x2,x3,x4,x5),
      _2150: (x0,x1,x2,x3) => x0.wire__crate__api__vector_store__vector_store_init(x1,x2,x3),
      _2151: (x0,x1) => x0.wire__crate__api__vector_store__vector_store_is_initialized(x1),
      _2152: (x0,x1,x2,x3) => x0.wire__crate__api__vector_store__vector_store_search(x1,x2,x3),
      _2154: (x0,x1,x2) => x0.wire__crate__api__vector_store__vector_store_upsert_batch(x1,x2),
      _2171: (x0,x1,x2) => x0.wire__crate__api__yns__parser__yns_parse(x1,x2),
      _2182: () => globalThis.wasm_bindgen,
      _2186: () => globalThis.wasm_bindgen.frb_get_rust_content_hash(),
      _2190: (x0,x1,x2) => x0.open(x1,x2),
      _2191: x0 => x0.abort(),
      _2192: x0 => x0.getAllResponseHeaders(),
      _2193: x0 => globalThis.wasm_bindgen(x0),
      _2194: (x0,x1) => x0.warn(x1),
      _2195: (x0,x1) => x0.item(x1),
      _2197: () => new AbortController(),
      _2198: x0 => x0.abort(),
      _2199: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _2200: (x0,x1) => globalThis.fetch(x0,x1),
      _2201: (x0,x1) => x0.get(x1),
      _2202: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._2202(f,arguments.length,x0,x1,x2) }),
      _2203: (x0,x1) => x0.forEach(x1),
      _2204: x0 => x0.getReader(),
      _2205: x0 => x0.cancel(),
      _2206: x0 => x0.read(),
      _2207: x0 => x0.trustedTypes,
      _2208: (x0,x1) => { x0.src = x1 },
      _2209: (x0,x1) => x0.createScriptURL(x1),
      _2210: x0 => x0.nonce,
      _2211: (x0,x1) => x0.debug(x1),
      _2212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2212(f,arguments.length,x0) }),
      _2213: x0 => ({createScriptURL: x0}),
      _2214: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _2215: (x0,x1) => x0.querySelectorAll(x1),
      _2216: (x0,x1) => x0.createImageBitmap(x1),
      _2398: (x0,x1) => { x0.fillColor = x1 },
      _2437: o => o instanceof Array,
      _2438: (a, i) => a.push(i),
      _2439: (a, i) => a.splice(i, 1)[0],
      _2441: (a, l) => a.length = l,
      _2442: a => a.pop(),
      _2443: (a, i) => a.splice(i, 1),
      _2444: (a, s) => a.join(s),
      _2445: (a, s, e) => a.slice(s, e),
      _2447: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _2448: a => a.length,
      _2449: (a, l) => a.length = l,
      _2450: (a, i) => a[i],
      _2451: (a, i, v) => a[i] = v,
      _2453: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _2454: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2455: o => o instanceof DataView,
      _2456: o => o instanceof Uint8Array,
      _2457: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2458: o => o instanceof Int8Array,
      _2459: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2460: o => o instanceof Uint8ClampedArray,
      _2461: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2462: o => o instanceof Uint16Array,
      _2463: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2464: o => o instanceof Int16Array,
      _2465: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2466: o => o instanceof Uint32Array,
      _2467: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2468: o => o instanceof Int32Array,
      _2469: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2471: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2472: o => o instanceof Float32Array,
      _2473: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2474: o => o instanceof Float64Array,
      _2475: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2476: (t, s) => t.set(s),
      _2477: l => new DataView(new ArrayBuffer(l)),
      _2478: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2479: o => o.byteLength,
      _2480: o => o.buffer,
      _2481: o => o.byteOffset,
      _2482: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2483: (b, o) => new DataView(b, o),
      _2484: (b, o, l) => new DataView(b, o, l),
      _2485: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2486: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2487: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2488: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2489: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2490: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2491: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2492: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2493: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2494: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2495: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2496: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2499: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2500: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2501: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2502: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2503: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2504: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2505: Function.prototype.call.bind(Number.prototype.toString),
      _2506: Function.prototype.call.bind(BigInt.prototype.toString),
      _2507: Function.prototype.call.bind(Number.prototype.toString),
      _2508: (d, digits) => d.toFixed(digits),
      _2515: (x0,x1,x2) => x0.toDataURL(x1,x2),
      _2519: x0 => new Function(x0),
      _2520: x0 => x0.call(),
      _2521: () => globalThis.crossOriginIsolated,
      _2522: x0 => globalThis.BigInt(x0),
      _2523: () => globalThis.document,
      _2524: () => globalThis.window,
      _2529: (x0,x1) => { x0.height = x1 },
      _2531: (x0,x1) => { x0.width = x1 },
      _2533: (x0,x1) => { x0.pointerEvents = x1 },
      _2536: x0 => x0.head,
      _2537: x0 => x0.classList,
      _2541: (x0,x1) => { x0.innerText = x1 },
      _2542: x0 => x0.style,
      _2544: x0 => x0.sheet,
      _2545: x0 => x0.src,
      _2546: (x0,x1) => { x0.src = x1 },
      _2547: x0 => x0.naturalWidth,
      _2548: x0 => x0.naturalHeight,
      _2555: x0 => x0.offsetX,
      _2556: x0 => x0.offsetY,
      _2557: x0 => x0.button,
      _2564: x0 => x0.status,
      _2565: (x0,x1) => { x0.responseType = x1 },
      _2567: x0 => x0.response,
      _2644: x0 => { globalThis.onGoogleLibraryLoad = x0 },
      _2645: (module,f) => finalizeWrapper(f, function() { return module.exports._2645(f,arguments.length) }),
      _2683: x0 => x0.readyState,
      _2685: (x0,x1) => { x0.timeout = x1 },
      _2687: (x0,x1) => { x0.withCredentials = x1 },
      _2688: x0 => x0.upload,
      _2689: x0 => x0.responseURL,
      _2690: x0 => x0.status,
      _2691: x0 => x0.statusText,
      _2693: (x0,x1) => { x0.responseType = x1 },
      _2694: x0 => x0.response,
      _2706: x0 => x0.loaded,
      _2707: x0 => x0.total,
      _2754: (x0,x1) => { x0.draggable = x1 },
      _2770: x0 => x0.style,
      _2783: (x0,x1) => { x0.oncancel = x1 },
      _2789: (x0,x1) => { x0.onchange = x1 },
      _2829: (x0,x1) => { x0.onerror = x1 },
      _2969: (x0,x1) => { x0.nonce = x1 },
      _3023: x0 => x0.content,
      _3129: (x0,x1) => { x0.download = x1 },
      _3154: (x0,x1) => { x0.href = x1 },
      _3202: (x0,x1) => { x0.src = x1 },
      _3696: (x0,x1) => { x0.accept = x1 },
      _3710: x0 => x0.files,
      _3736: (x0,x1) => { x0.multiple = x1 },
      _3754: (x0,x1) => { x0.type = x1 },
      _4003: x0 => x0.src,
      _4004: (x0,x1) => { x0.src = x1 },
      _4006: (x0,x1) => { x0.type = x1 },
      _4010: (x0,x1) => { x0.async = x1 },
      _4012: (x0,x1) => { x0.defer = x1 },
      _4024: (x0,x1) => { x0.charset = x1 },
      _4049: (x0,x1) => { x0.width = x1 },
      _4051: (x0,x1) => { x0.height = x1 },
      _4471: () => globalThis.window,
      _4511: x0 => x0.document,
      _4514: x0 => x0.location,
      _4533: x0 => x0.navigator,
      _4788: x0 => x0.isSecureContext,
      _4791: x0 => x0.crypto,
      _4795: x0 => x0.trustedTypes,
      _4796: x0 => x0.sessionStorage,
      _4797: x0 => x0.localStorage,
      _4805: x0 => x0.href,
      _4856: x0 => x0.message,
      _4899: x0 => x0.clipboard,
      _4901: x0 => x0.geolocation,
      _4904: x0 => x0.mediaDevices,
      _4906: x0 => x0.permissions,
      _4907: x0 => x0.maxTouchPoints,
      _4914: x0 => x0.appCodeName,
      _4915: x0 => x0.appName,
      _4916: x0 => x0.appVersion,
      _4917: x0 => x0.platform,
      _4918: x0 => x0.product,
      _4919: x0 => x0.productSub,
      _4920: x0 => x0.userAgent,
      _4921: x0 => x0.vendor,
      _4922: x0 => x0.vendorSub,
      _4924: x0 => x0.language,
      _4925: x0 => x0.languages,
      _4926: x0 => x0.onLine,
      _4931: x0 => x0.hardwareConcurrency,
      _4933: x0 => x0.storage,
      _4953: x0 => x0.width,
      _4954: x0 => x0.height,
      _4970: x0 => x0.data,
      _5000: x0 => x0.port1,
      _5001: x0 => x0.port2,
      _5003: (x0,x1) => { x0.onmessage = x1 },
      _5081: x0 => x0.port,
      _5116: x0 => x0.length,
      _7018: x0 => x0.type,
      _7019: x0 => x0.target,
      _7059: x0 => x0.signal,
      _7068: x0 => x0.length,
      _7070: x0 => x0.length,
      _7110: x0 => x0.baseURI,
      _7116: x0 => x0.firstChild,
      _7127: () => globalThis.document,
      _7208: x0 => x0.body,
      _7210: x0 => x0.head,
      _7539: (x0,x1) => { x0.id = x1 },
      _7566: x0 => x0.children,
      _8885: x0 => x0.value,
      _8887: x0 => x0.done,
      _9050: x0 => x0.size,
      _9051: x0 => x0.type,
      _9057: x0 => x0.name,
      _9058: x0 => x0.lastModified,
      _9063: x0 => x0.length,
      _9068: x0 => x0.result,
      _9564: x0 => x0.url,
      _9566: x0 => x0.status,
      _9568: x0 => x0.statusText,
      _9569: x0 => x0.headers,
      _9570: x0 => x0.body,
      _11018: x0 => x0.result,
      _11019: x0 => x0.error,
      _11030: (x0,x1) => { x0.onupgradeneeded = x1 },
      _11032: x0 => x0.oldVersion,
      _11111: x0 => x0.key,
      _11112: x0 => x0.primaryKey,
      _11114: x0 => x0.value,
      _11952: (x0,x1) => { x0.display = x1 },
      _12116: (x0,x1) => { x0.height = x1 },
      _12288: (x0,x1) => { x0.maxWidth = x1 },
      _12806: (x0,x1) => { x0.width = x1 },
      _13174: x0 => x0.name,
      _13175: x0 => x0.message,
      _13178: x0 => x0.subtle,
      _13882: () => globalThis.console,
      _13908: () => globalThis.speechSynthesis,
      _13909: (x0,x1) => { x0.lang = x1 },
      _13911: (x0,x1) => { x0.pitch = x1 },
      _13914: (x0,x1) => { x0.rate = x1 },
      _13916: (x0,x1) => { x0.text = x1 },
      _13917: (x0,x1) => { x0.voice = x1 },
      _13918: x0 => x0.voice,
      _13920: (x0,x1) => { x0.volume = x1 },
      _13921: (x0,x1) => { x0.onstart = x1 },
      _13922: (x0,x1) => { x0.onend = x1 },
      _13923: (x0,x1) => { x0.onpause = x1 },
      _13924: (x0,x1) => { x0.onresume = x1 },
      _13925: (x0,x1) => { x0.onerror = x1 },
      _13926: (x0,x1) => { x0.onboundary = x1 },
      _13928: x0 => x0.lang,
      _13929: x0 => x0.localService,
      _13930: x0 => x0.name,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      s: [
        "([ \r\n\t]+)|([!-\\[\\]-‧‪-퟿豈-￿][̀-ͯ]*|[\ud800-\udbff][\udc00-\udfff][̀-ͯ]*|\\\\verb\\*([^]).*?\\3|\\\\verb([^*a-zA-Z]).*?\\4|\\\\operatorname\\*|\\\\[a-zA-Z@]+[ \r\n\t]*|\\\\[^\ud800-\udfff])",
      ],
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
