// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _17: (x0,x1) => x0.get(x1),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _140: (x0,x1) => x0.appendChild(x1),
      _171: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _172: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _173: (x0,x1) => new OffscreenCanvas(x0,x1),
      _174: x0 => x0.remove(),
      _175: (x0,x1) => x0.append(x1),
      _177: x0 => x0.unlock(),
      _178: x0 => x0.getReader(),
      _179: (x0,x1) => x0.item(x1),
      _180: x0 => x0.next(),
      _181: x0 => x0.now(),
      _182: (x0,x1) => x0.revokeObjectURL(x1),
      _183: x0 => x0.close(),
      _184: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _185: x0 => new window.ImageDecoder(x0),
      _186: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _187: (x0,x1) => x0.decode(x1),
      _188: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._188(f,arguments.length,x0) }),
      _189: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _191: (x0,x1) => x0.getModifierState(x1),
      _192: x0 => x0.preventDefault(),
      _193: x0 => x0.stopPropagation(),
      _194: (x0,x1) => x0.removeProperty(x1),
      _195: (x0,x1) => x0.prepend(x1),
      _196: x0 => new Intl.Locale(x0),
      _197: (x0,x1) => x0.observe(x1),
      _198: x0 => x0.disconnect(),
      _199: (x0,x1) => x0.getAttribute(x1),
      _200: (x0,x1) => x0.contains(x1),
      _201: (x0,x1) => x0.querySelector(x1),
      _202: (x0,x1) => x0.matchMedia(x1),
      _203: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._203(f,arguments.length,x0) }),
      _204: (x0,x1,x2) => x0.call(x1,x2),
      _205: x0 => x0.blur(),
      _206: x0 => x0.hasFocus(),
      _207: (x0,x1) => x0.removeAttribute(x1),
      _208: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _209: (x0,x1) => x0.hasAttribute(x1),
      _210: (x0,x1) => x0.getModifierState(x1),
      _211: (x0,x1) => x0.createTextNode(x1),
      _212: x0 => x0.getBoundingClientRect(),
      _213: (x0,x1) => x0.closest(x1),
      _214: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _729: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _754: x0 => x0.baseURI,
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _760: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _822: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _830: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _842: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _919: x0 => x0.headers,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1012: x0 => x0.matches,
      _1016: x0 => x0.relatedTarget,
      _1018: x0 => x0.clientX,
      _1019: x0 => x0.clientY,
      _1020: x0 => x0.offsetX,
      _1021: x0 => x0.offsetY,
      _1024: x0 => x0.button,
      _1025: x0 => x0.buttons,
      _1026: x0 => x0.ctrlKey,
      _1030: x0 => x0.pointerId,
      _1031: x0 => x0.pointerType,
      _1032: x0 => x0.pressure,
      _1033: x0 => x0.tiltX,
      _1034: x0 => x0.tiltY,
      _1035: x0 => x0.getCoalescedEvents(),
      _1038: x0 => x0.deltaX,
      _1039: x0 => x0.deltaY,
      _1040: x0 => x0.wheelDeltaX,
      _1041: x0 => x0.wheelDeltaY,
      _1042: x0 => x0.deltaMode,
      _1049: x0 => x0.changedTouches,
      _1052: x0 => x0.clientX,
      _1053: x0 => x0.clientY,
      _1056: x0 => x0.data,
      _1059: (x0,x1) => { x0.disabled = x1 },
      _1061: (x0,x1) => { x0.type = x1 },
      _1062: (x0,x1) => { x0.max = x1 },
      _1063: (x0,x1) => { x0.min = x1 },
      _1064: x0 => x0.value,
      _1065: (x0,x1) => { x0.value = x1 },
      _1066: x0 => x0.disabled,
      _1067: (x0,x1) => { x0.disabled = x1 },
      _1069: (x0,x1) => { x0.placeholder = x1 },
      _1071: (x0,x1) => { x0.name = x1 },
      _1072: (x0,x1) => { x0.autocomplete = x1 },
      _1074: x0 => x0.selectionDirection,
      _1075: x0 => x0.selectionStart,
      _1077: x0 => x0.selectionEnd,
      _1080: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1081: (x0,x1) => x0.add(x1),
      _1084: (x0,x1) => { x0.noValidate = x1 },
      _1085: (x0,x1) => { x0.method = x1 },
      _1086: (x0,x1) => { x0.action = x1 },
      _1092: (x0,x1) => x0.getContext(x1),
      _1094: x0 => x0.convertToBlob(),
      _1111: x0 => x0.orientation,
      _1112: x0 => x0.width,
      _1113: x0 => x0.height,
      _1114: (x0,x1) => x0.lock(x1),
      _1133: x0 => new ResizeObserver(x0),
      _1136: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1136(f,arguments.length,x0,x1) }),
      _1144: x0 => x0.length,
      _1145: x0 => x0.iterator,
      _1146: x0 => x0.Segmenter,
      _1147: x0 => x0.v8BreakIterator,
      _1148: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1151: x0 => x0.language,
      _1152: x0 => x0.script,
      _1153: x0 => x0.region,
      _1171: x0 => x0.done,
      _1172: x0 => x0.value,
      _1173: x0 => x0.index,
      _1177: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1178: (x0,x1) => x0.adoptText(x1),
      _1179: x0 => x0.first(),
      _1180: x0 => x0.next(),
      _1181: x0 => x0.current(),
      _1194: x0 => x0.hostElement,
      _1195: x0 => x0.viewConstraints,
      _1198: x0 => x0.maxHeight,
      _1199: x0 => x0.maxWidth,
      _1200: x0 => x0.minHeight,
      _1201: x0 => x0.minWidth,
      _1202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1202(f,arguments.length,x0) }),
      _1203: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1203(f,arguments.length,x0) }),
      _1204: (x0,x1) => ({addView: x0,removeView: x1}),
      _1207: x0 => x0.loader,
      _1208: () => globalThis._flutter,
      _1209: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1210: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1210(f,arguments.length,x0) }),
      _1211: (module,f) => finalizeWrapper(f, function() { return module.exports._1211(f,arguments.length) }),
      _1212: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1215: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1215(f,arguments.length,x0) }),
      _1216: x0 => ({runApp: x0}),
      _1218: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1218(f,arguments.length,x0,x1) }),
      _1219: x0 => new Promise(x0),
      _1220: x0 => x0.length,
      _1221: () => globalThis.window.ImageDecoder,
      _1222: x0 => x0.tracks,
      _1224: x0 => x0.completed,
      _1226: x0 => x0.image,
      _1232: x0 => x0.displayWidth,
      _1233: x0 => x0.displayHeight,
      _1234: x0 => x0.duration,
      _1237: x0 => x0.ready,
      _1238: x0 => x0.selectedTrack,
      _1239: x0 => x0.repetitionCount,
      _1240: x0 => x0.frameCount,
      _1285: (x0,x1) => x0.createElement(x1),
      _1286: (x0,x1) => x0.querySelector(x1),
      _1287: (x0,x1) => x0.appendChild(x1),
      _1288: x0 => ({type: x0}),
      _1289: (x0,x1) => new Blob(x0,x1),
      _1290: x0 => globalThis.URL.createObjectURL(x0),
      _1292: (x0,x1,x2,x3) => x0.sendCommand(x1,x2,x3),
      _1293: () => globalThis.PdfiumWasmCommunicator,
      _1295: x0 => { globalThis.pdfiumWasmWorkerUrl = x0 },
      _1296: (x0,x1) => x0.writeText(x1),
      _1297: x0 => x0.preventDefault(),
      _1298: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1298(f,arguments.length,x0) }),
      _1299: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1307: x0 => x0.createRange(),
      _1308: (x0,x1) => x0.selectNode(x1),
      _1309: x0 => x0.getSelection(),
      _1310: x0 => x0.removeAllRanges(),
      _1311: (x0,x1) => x0.addRange(x1),
      _1312: (x0,x1) => x0.createElement(x1),
      _1313: (x0,x1) => x0.append(x1),
      _1314: (x0,x1,x2) => x0.insertRule(x1,x2),
      _1315: (x0,x1) => x0.add(x1),
      _1316: x0 => x0.preventDefault(),
      _1317: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1317(f,arguments.length,x0) }),
      _1318: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1319: () => globalThis.window.navigator.userAgent,
      _1320: (x0,x1) => x0.append(x1),
      _1321: x0 => x0.remove(),
      _1322: (x0,x1) => x0.removeItem(x1),
      _1323: (x0,x1) => x0.getItem(x1),
      _1324: x0 => globalThis.URL.revokeObjectURL(x0),
      _1326: (x0,x1,x2,x3,x4,x5) => x0.drawImage(x1,x2,x3,x4,x5),
      _1329: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1329(f,arguments.length,x0) }),
      _1330: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1330(f,arguments.length,x0) }),
      _1331: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1331(f,arguments.length,x0) }),
      _1332: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1333: (x0,x1) => x0.replaceChildren(x1),
      _1334: x0 => x0.click(),
      _1335: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24) => ({aspectRatio: x0,background: x1,center: x2,checkCrossOrigin: x3,checkOrientation: x4,cropBoxMovable: x5,cropBoxResizable: x6,dragMode: x7,guides: x8,highlight: x9,initialAspectRatio: x10,minContainerHeight: x11,minContainerWidth: x12,minCropBoxHeight: x13,minCropBoxWidth: x14,modal: x15,movable: x16,rotatable: x17,scalable: x18,toggleDragModeOnDblclick: x19,viewMode: x20,wheelZoomRatio: x21,zoomOnTouch: x22,zoomOnWheel: x23,zoomable: x24}),
      _1336: (x0,x1) => new Cropper(x0,x1),
      _1337: () => ({}),
      _1338: (x0,x1) => x0.getCroppedCanvas(x1),
      _1339: x0 => x0.getCroppedCanvas(),
      _1340: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1340(f,arguments.length,x0) }),
      _1341: (x0,x1,x2) => x0.toBlob(x1,x2),
      _1342: (x0,x1) => x0.rotate(x1),
      _1343: (x0,x1) => x0.scale(x1),
      _1344: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1345: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1347: (x0,x1) => x0.getAttribute(x1),
      _1351: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1352: (x0,x1) => x0.canShare(x1),
      _1353: (x0,x1) => x0.share(x1),
      _1355: (x0,x1,x2) => ({files: x0,title: x1,text: x2}),
      _1356: (x0,x1) => ({files: x0,text: x1}),
      _1357: (x0,x1) => ({files: x0,title: x1}),
      _1358: x0 => ({files: x0}),
      _1359: (x0,x1) => ({title: x0,text: x1}),
      _1361: () => ({}),
      _1362: (x0,x1,x2) => new File(x0,x1,x2),
      _1372: (x0,x1) => x0.item(x1),
      _1373: x0 => x0.decode(),
      _1374: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1375: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1376: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1376(f,arguments.length,x0) }),
      _1377: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1377(f,arguments.length,x0) }),
      _1378: x0 => x0.send(),
      _1379: () => new XMLHttpRequest(),
      _1380: (x0,x1) => x0.key(x1),
      _1381: (x0,x1,x2) => x0.setItem(x1,x2),
      _1397: (x0,x1) => x0.item(x1),
      _1398: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1398(f,arguments.length,x0) }),
      _1413: (x0,x1) => x0.getContext(x1),
      _1414: (x0,x1,x2,x3,x4) => x0.clearRect(x1,x2,x3,x4),
      _1415: x0 => x0.close(),
      _1416: () => new FileReader(),
      _1418: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1419: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1419(f,arguments.length,x0) }),
      _1420: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1421: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1421(f,arguments.length,x0) }),
      _1422: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1422(f,arguments.length,x0) }),
      _1423: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1423(f,arguments.length,x0) }),
      _1424: (x0,x1) => x0.removeChild(x1),
      _1425: x0 => new Blob(x0),
      _1427: x0 => x0.deviceMemory,
      _1428: () => new SpeechSynthesisUtterance(),
      _1429: x0 => x0.pause(),
      _1430: x0 => x0.resume(),
      _1431: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1431(f,arguments.length,x0) }),
      _1432: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1432(f,arguments.length,x0) }),
      _1433: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1433(f,arguments.length,x0) }),
      _1434: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1434(f,arguments.length,x0) }),
      _1435: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1435(f,arguments.length,x0) }),
      _1436: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1436(f,arguments.length,x0) }),
      _1437: (x0,x1) => x0.speak(x1),
      _1438: x0 => x0.cancel(),
      _1439: x0 => x0.getVoices(),
      _1440: () => globalThis.Intl.DateTimeFormat(),
      _1441: x0 => x0.resolvedOptions(),
      _1442: () => globalThis.Intl.supportedValuesOf,
      _1444: x0 => x0.timeZone,
      _1445: (x0,x1,x2,x3,x4,x5,x6,x7) => x0.unwrapKey(x1,x2,x3,x4,x5,x6,x7),
      _1446: (x0,x1,x2,x3,x4,x5) => x0.importKey(x1,x2,x3,x4,x5),
      _1447: (x0,x1,x2,x3) => x0.generateKey(x1,x2,x3),
      _1448: (x0,x1,x2,x3,x4) => x0.wrapKey(x1,x2,x3,x4),
      _1449: (x0,x1,x2) => x0.exportKey(x1,x2),
      _1450: (x0,x1) => x0.getRandomValues(x1),
      _1451: (x0,x1,x2,x3) => x0.encrypt(x1,x2,x3),
      _1452: (x0,x1,x2,x3) => x0.decrypt(x1,x2,x3),
      _1462: Date.now,
      _1464: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1465: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1466: () => new Error().stack,
      _1467: () => typeof dartUseDateNowForTicks !== "undefined",
      _1468: () => 1000 * performance.now(),
      _1469: () => Date.now(),
      _1470: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1471: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1472: () => new WeakMap(),
      _1473: (map, o) => map.get(o),
      _1474: (map, o, v) => map.set(o, v),
      _1475: (exn) => exn.toString(),
      _1476: (exn) => exn.stack,
      _1477: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1478: x0 => new WeakRef(x0),
      _1479: x0 => x0.deref(),
      _1480: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1480(f,arguments.length,x0) }),
      _1481: x0 => new FinalizationRegistry(x0),
      _1482: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _1484: (x0,x1) => x0.unregister(x1),
      _1486: () => globalThis.WeakRef,
      _1487: () => globalThis.FinalizationRegistry,
      _1489: x0 => x0.call(),
      _1490: s => JSON.stringify(s),
      _1491: s => printToConsole(s),
      _1492: o => {
        if (o === null || o === undefined) return 0;
        if (typeof(o) === 'string') return 1;
        return 2;
      },
      _1493: (o, p, r) => o.replaceAll(p, () => r),
      _1494: (o, p, r) => o.replace(p, () => r),
      _1495: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1496: s => s.toUpperCase(),
      _1497: s => s.trim(),
      _1498: s => s.trimLeft(),
      _1499: s => s.trimRight(),
      _1500: (string, times) => string.repeat(times),
      _1501: Function.prototype.call.bind(String.prototype.indexOf),
      _1502: (s, p, i) => s.lastIndexOf(p, i),
      _1503: (string, token) => string.split(token),
      _1504: Object.is,
      _1507: (o, t) => typeof o === t,
      _1508: (o, c) => o instanceof c,
      _1509: o => Object.keys(o),
      _1512: (o, a) => o + a,
      _1522: (o, a) => o == a,
      _1539: x0 => new Array(x0),
      _1541: x0 => x0.length,
      _1543: (x0,x1) => x0[x1],
      _1544: (x0,x1,x2) => { x0[x1] = x2 },
      _1547: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1549: x0 => new Int8Array(x0),
      _1550: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1552: x0 => new Uint8ClampedArray(x0),
      _1554: x0 => new Int16Array(x0),
      _1556: x0 => new Uint16Array(x0),
      _1558: x0 => new Int32Array(x0),
      _1560: x0 => new Uint32Array(x0),
      _1562: x0 => new Float32Array(x0),
      _1564: x0 => new Float64Array(x0),
      _1585: (x0,x1) => x0.call(x1),
      _1588: x0 => x0.random(),
      _1589: (x0,x1) => x0.getRandomValues(x1),
      _1590: () => globalThis.crypto,
      _1591: () => globalThis.Math,
      _1593: () => globalThis.performance,
      _1594: () => globalThis.JSON,
      _1595: x0 => x0.measure,
      _1596: x0 => x0.mark,
      _1597: x0 => x0.clearMeasures,
      _1598: x0 => x0.clearMarks,
      _1599: (x0,x1,x2,x3) => x0.measure(x1,x2,x3),
      _1600: (x0,x1,x2) => x0.mark(x1,x2),
      _1601: x0 => x0.clearMeasures(),
      _1602: x0 => x0.clearMarks(),
      _1603: (x0,x1) => x0.parse(x1),
      _1604: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1605: (handle) => clearTimeout(handle),
      _1606: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1607: (handle) => clearInterval(handle),
      _1608: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1609: () => Date.now(),
      _1610: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1611: (x0,x1) => x0.exec(x1),
      _1612: (x0,x1) => x0.test(x1),
      _1613: x0 => x0.pop(),
      _1615: o => o === undefined,
      _1617: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1619: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1620: o => o instanceof RegExp,
      _1621: (l, r) => l === r,
      _1622: o => o,
      _1623: o => {
        if (o === undefined || o === null) return 0;
        if (typeof o === 'number') return 1;
        return 2;
      },
      _1624: o => o,
      _1625: o => {
        if (o === undefined || o === null) return 0;
        if (typeof o === 'boolean') return 1;
        return 2;
      },
      _1626: o => o,
      _1627: b => !!b,
      _1628: o => o.length,
      _1630: (o, i) => o[i],
      _1631: f => f.dartFunction,
      _1632: () => ({}),
      _1633: () => [],
      _1635: () => globalThis,
      _1636: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1637: (o, p) => p in o,
      _1638: (o, p) => o[p],
      _1639: (o, p, v) => o[p] = v,
      _1640: (o, m, a) => o[m].apply(o, a),
      _1642: o => String(o),
      _1643: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1644: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1644(f,arguments.length,x0) }),
      _1645: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1645(f,arguments.length,x0,x1) }),
      _1646: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1647: o => [o],
      _1648: (o0, o1) => [o0, o1],
      _1649: (o0, o1, o2) => [o0, o1, o2],
      _1650: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1651: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1652: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1653: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1654: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1655: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1656: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1657: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1658: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1659: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1660: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1661: x0 => new ArrayBuffer(x0),
      _1662: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1663: x0 => x0.input,
      _1664: x0 => x0.index,
      _1665: x0 => x0.groups,
      _1666: x0 => x0.flags,
      _1667: x0 => x0.multiline,
      _1668: x0 => x0.ignoreCase,
      _1669: x0 => x0.unicode,
      _1670: x0 => x0.dotAll,
      _1671: (x0,x1) => { x0.lastIndex = x1 },
      _1672: (o, p) => p in o,
      _1673: (o, p) => o[p],
      _1674: (o, p, v) => o[p] = v,
      _1676: x0 => x0.exports,
      _1677: (x0,x1) => globalThis.WebAssembly.instantiateStreaming(x0,x1),
      _1678: x0 => x0.instance,
      _1680: x0 => new WebAssembly.Memory(x0),
      _1681: x0 => x0.buffer,
      _1684: x0 => x0.arrayBuffer(),
      _1686: x0 => x0.sqlite3_initialize,
      _1688: (x0,x1,x2,x3,x4) => x0.sqlite3_open_v2(x1,x2,x3,x4),
      _1689: (x0,x1) => x0.sqlite3_close_v2(x1),
      _1690: (x0,x1,x2) => x0.sqlite3_extended_result_codes(x1,x2),
      _1691: (x0,x1) => x0.sqlite3_extended_errcode(x1),
      _1692: (x0,x1) => x0.sqlite3_errmsg(x1),
      _1693: (x0,x1) => x0.sqlite3_errstr(x1),
      _1694: x0 => x0.sqlite3_error_offset,
      _1698: (x0,x1) => x0.sqlite3_last_insert_rowid(x1),
      _1699: (x0,x1) => x0.sqlite3_changes(x1),
      _1700: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_exec(x1,x2,x3,x4,x5),
      _1703: (x0,x1,x2,x3,x4,x5,x6) => x0.sqlite3_prepare_v3(x1,x2,x3,x4,x5,x6),
      _1704: (x0,x1) => x0.sqlite3_finalize(x1),
      _1705: (x0,x1) => x0.sqlite3_step(x1),
      _1706: (x0,x1) => x0.sqlite3_reset(x1),
      _1707: (x0,x1) => x0.sqlite3_stmt_isexplain(x1),
      _1709: (x0,x1) => x0.sqlite3_column_count(x1),
      _1710: (x0,x1) => x0.sqlite3_bind_parameter_count(x1),
      _1712: (x0,x1,x2) => x0.sqlite3_column_name(x1,x2),
      _1713: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_bind_blob64(x1,x2,x3,x4,x5),
      _1714: (x0,x1,x2,x3) => x0.sqlite3_bind_double(x1,x2,x3),
      _1715: (x0,x1,x2,x3) => x0.sqlite3_bind_int64(x1,x2,x3),
      _1716: (x0,x1,x2) => x0.sqlite3_bind_null(x1,x2),
      _1717: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_bind_text(x1,x2,x3,x4,x5),
      _1718: (x0,x1,x2) => x0.sqlite3_column_blob(x1,x2),
      _1719: (x0,x1,x2) => x0.sqlite3_column_double(x1,x2),
      _1720: (x0,x1,x2) => x0.sqlite3_column_int64(x1,x2),
      _1721: (x0,x1,x2) => x0.sqlite3_column_text(x1,x2),
      _1722: (x0,x1,x2) => x0.sqlite3_column_bytes(x1,x2),
      _1723: (x0,x1,x2) => x0.sqlite3_column_type(x1,x2),
      _1724: (x0,x1) => x0.sqlite3_value_blob(x1),
      _1725: (x0,x1) => x0.sqlite3_value_double(x1),
      _1726: (x0,x1) => x0.sqlite3_value_type(x1),
      _1727: (x0,x1) => x0.sqlite3_value_int64(x1),
      _1728: (x0,x1) => x0.sqlite3_value_text(x1),
      _1729: (x0,x1) => x0.sqlite3_value_bytes(x1),
      _1732: (x0,x1) => x0.sqlite3_user_data(x1),
      _1733: (x0,x1,x2,x3,x4) => x0.sqlite3_result_blob64(x1,x2,x3,x4),
      _1734: (x0,x1,x2) => x0.sqlite3_result_double(x1,x2),
      _1735: (x0,x1,x2,x3) => x0.sqlite3_result_error(x1,x2,x3),
      _1736: (x0,x1,x2) => x0.sqlite3_result_int64(x1,x2),
      _1737: (x0,x1) => x0.sqlite3_result_null(x1),
      _1738: (x0,x1,x2,x3,x4) => x0.sqlite3_result_text(x1,x2,x3,x4),
      _1739: x0 => x0.sqlite3_result_subtype,
      _1758: (x0,x1) => x0.dart_sqlite3_malloc(x1),
      _1759: (x0,x1) => x0.dart_sqlite3_free(x1),
      _1760: (x0,x1,x2,x3) => x0.dart_sqlite3_register_vfs(x1,x2,x3),
      _1761: (x0,x1,x2,x3,x4,x5) => x0.dart_sqlite3_create_scalar_function(x1,x2,x3,x4,x5),
      _1764: x0 => x0.dart_sqlite3_updates,
      _1765: x0 => x0.dart_sqlite3_commits,
      _1766: x0 => x0.dart_sqlite3_rollbacks,
      _1770: x0 => ({initial: x0}),
      _1771: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1771(f,arguments.length,x0) }),
      _1772: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1772(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1773: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1773(f,arguments.length,x0,x1,x2) }),
      _1774: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1774(f,arguments.length,x0,x1,x2,x3) }),
      _1775: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1775(f,arguments.length,x0,x1,x2,x3) }),
      _1776: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1776(f,arguments.length,x0,x1,x2) }),
      _1777: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1777(f,arguments.length,x0,x1) }),
      _1778: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1778(f,arguments.length,x0,x1) }),
      _1779: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1779(f,arguments.length,x0) }),
      _1780: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1780(f,arguments.length,x0) }),
      _1781: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1781(f,arguments.length,x0,x1,x2,x3) }),
      _1782: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1782(f,arguments.length,x0,x1,x2,x3) }),
      _1783: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1783(f,arguments.length,x0,x1) }),
      _1784: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1784(f,arguments.length,x0,x1) }),
      _1785: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1785(f,arguments.length,x0,x1) }),
      _1786: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1786(f,arguments.length,x0,x1) }),
      _1787: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1787(f,arguments.length,x0,x1) }),
      _1788: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1788(f,arguments.length,x0,x1) }),
      _1789: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1789(f,arguments.length,x0,x1,x2) }),
      _1790: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1790(f,arguments.length,x0,x1,x2) }),
      _1791: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1791(f,arguments.length,x0,x1,x2) }),
      _1792: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1792(f,arguments.length,x0) }),
      _1793: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1793(f,arguments.length,x0) }),
      _1794: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1794(f,arguments.length,x0) }),
      _1795: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1795(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1796: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1796(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1797: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1797(f,arguments.length,x0) }),
      _1798: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1798(f,arguments.length,x0) }),
      _1799: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1799(f,arguments.length,x0,x1) }),
      _1800: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1800(f,arguments.length,x0,x1) }),
      _1801: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1801(f,arguments.length,x0,x1,x2) }),
      _1803: (x0,x1,x2,x3) => x0.call(x1,x2,x3),
      _1808: x0 => new URL(x0),
      _1809: (x0,x1) => new URL(x0,x1),
      _1810: (x0,x1) => globalThis.fetch(x0,x1),
      _1811: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1812: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1814: (x0,x1) => ({i: x0,p: x1}),
      _1815: (x0,x1) => ({c: x0,r: x1}),
      _1816: x0 => x0.i,
      _1817: x0 => x0.p,
      _1818: x0 => x0.c,
      _1819: x0 => x0.r,
      _1820: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1820(f,arguments.length,x0) }),
      _1821: (x0,x1) => x0.postMessage(x1),
      _1822: x0 => x0.close(),
      _1824: x0 => new Worker(x0),
      _1826: x0 => x0.getDirectory(),
      _1827: x0 => ({create: x0}),
      _1828: (x0,x1,x2) => x0.getFileHandle(x1,x2),
      _1829: x0 => x0.createSyncAccessHandle(),
      _1830: x0 => x0.close(),
      _1833: x0 => x0.close(),
      _1836: (x0,x1,x2) => x0.open(x1,x2),
      _1840: (x0,x1,x2) => x0.getDirectoryHandle(x1,x2),
      _1845: x0 => ({create: x0}),
      _1850: (x0,x1) => new SharedWorker(x0,x1),
      _1851: x0 => x0.start(),
      _1852: x0 => x0.terminate(),
      _1853: () => new MessageChannel(),
      _1857: x0 => new SharedArrayBuffer(x0),
      _1858: x0 => ({at: x0}),
      _1859: x0 => x0.getSize(),
      _1860: (x0,x1) => x0.truncate(x1),
      _1861: x0 => x0.flush(),
      _1864: x0 => x0.synchronizationBuffer,
      _1865: x0 => x0.communicationBuffer,
      _1866: (x0,x1,x2,x3) => ({clientVersion: x0,root: x1,synchronizationBuffer: x2,communicationBuffer: x3}),
      _1867: (x0,x1) => globalThis.IDBKeyRange.bound(x0,x1),
      _1868: x0 => ({autoIncrement: x0}),
      _1869: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      _1870: x0 => ({unique: x0}),
      _1871: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      _1872: (x0,x1) => x0.createObjectStore(x1),
      _1873: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1873(f,arguments.length,x0) }),
      _1874: (x0,x1,x2) => x0.transaction(x1,x2),
      _1875: (x0,x1) => x0.objectStore(x1),
      _1877: (x0,x1) => x0.index(x1),
      _1878: x0 => x0.openKeyCursor(),
      _1879: (x0,x1) => x0.getKey(x1),
      _1880: (x0,x1) => ({name: x0,length: x1}),
      _1881: (x0,x1) => x0.put(x1),
      _1882: (x0,x1) => x0.get(x1),
      _1883: (x0,x1) => x0.openCursor(x1),
      _1884: x0 => globalThis.IDBKeyRange.only(x0),
      _1885: (x0,x1,x2) => x0.put(x1,x2),
      _1886: (x0,x1) => x0.update(x1),
      _1887: (x0,x1) => x0.delete(x1),
      _1888: x0 => x0.name,
      _1889: x0 => x0.length,
      _1892: x0 => x0.continue(),
      _1893: () => globalThis.indexedDB,
      _1894: () => globalThis.navigator,
      _1895: (x0,x1) => x0.read(x1),
      _1896: (x0,x1,x2) => x0.read(x1,x2),
      _1897: (x0,x1) => x0.write(x1),
      _1898: (x0,x1,x2) => x0.write(x1,x2),
      _1900: (x0,x1,x2) => globalThis.Atomics.wait(x0,x1,x2),
      _1902: (x0,x1,x2) => globalThis.Atomics.notify(x0,x1,x2),
      _1903: (x0,x1,x2) => globalThis.Atomics.store(x0,x1,x2),
      _1904: (x0,x1) => globalThis.Atomics.load(x0,x1),
      _1905: () => globalThis.Int32Array,
      _1907: () => globalThis.Uint8Array,
      _1909: () => globalThis.DataView,
      _1911: x0 => x0.byteLength,
      _1913: x0 => globalThis.BigInt(x0),
      _1914: x0 => globalThis.Number(x0),
      _1921: x0 => new BroadcastChannel(x0),
      _1922: x0 => globalThis.Array.isArray(x0),
      _1923: (x0,x1) => x0.postMessage(x1),
      _1925: (x0,x1) => ({kind: x0,table: x1}),
      _1926: x0 => x0.kind,
      _1927: x0 => x0.table,
      _1928: () => new XMLHttpRequest(),
      _1929: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1931: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1932: (x0,x1) => x0.send(x1),
      _1933: x0 => x0.send(),
      _1935: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1935(f,arguments.length,x0) }),
      _1936: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1936(f,arguments.length,x0) }),
      _1970: (x0,x1,x2) => x0.wire__crate__api__pdf__extractor__analyze_pdf_pages(x1,x2),
      _2000: (x0,x1,x2) => x0.wire__crate__api__count_words(x1,x2),
      _2007: (x0,x1,x2,x3) => x0.wire__crate__api__security__decrypt(x1,x2,x3),
      _2012: (x0,x1,x2,x3) => x0.wire__crate__api__security__derive_key(x1,x2,x3),
      _2019: (x0,x1,x2) => x0.wire__crate__api__embeddings__embeddings_init(x1,x2),
      _2022: (x0,x1,x2,x3) => x0.wire__crate__api__security__encrypt(x1,x2,x3),
      _2036: (x0,x1,x2) => x0.wire__crate__api__pdf__extractor__extract_document_spans(x1,x2),
      _2040: (x0,x1,x2) => x0.wire__crate__api__fibonacci(x1,x2),
      _2049: (x0,x1,x2) => x0.wire__crate__api__embeddings__generate_embedding(x1,x2),
      _2051: (x0,x1,x2) => x0.wire__crate__api__generate_id(x1,x2),
      _2054: (x0,x1) => x0.wire__crate__api__security__generate_salt(x1),
      _2067: (x0,x1,x2) => x0.wire__crate__api__markdown__get_markdown_chunk_count(x1,x2),
      _2079: (x0,x1,x2) => x0.wire__crate__api__graph__graph_compute_depths(x1,x2),
      _2080: (x0,x1,x2,x3) => x0.wire__crate__api__graph__graph_create(x1,x2,x3),
      _2081: (x0,x1) => x0.wire__crate__api__graph__graph_destroy(x1),
      _2082: (x0,x1) => x0.wire__crate__api__graph__graph_get_edges(x1),
      _2083: (x0,x1) => x0.wire__crate__api__graph__graph_get_nodes(x1),
      _2085: (x0,x1,x2) => x0.wire__crate__api__graph__graph_simulate(x1,x2),
      _2086: (x0,x1) => x0.wire__crate__api__graph__graph_tick(x1),
      _2087: (x0,x1,x2) => x0.wire__crate__api__greet(x1,x2),
      _2096: (x0,x1,x2) => x0.wire__crate__api__is_prime(x1,x2),
      _2117: (x0,x1,x2,x3) => x0.wire__crate__api__markdown__parse_markdown_chunk(x1,x2,x3),
      _2118: (x0,x1,x2) => x0.wire__crate__api__markdown__parse_markdown_full(x1,x2),
      _2121: (x0,x1,x2) => x0.wire__crate__api__memory_import__parse_memory_anki(x1,x2),
      _2122: (x0,x1,x2) => x0.wire__crate__api__memory_import__parse_memory_json(x1,x2),
      _2123: (x0,x1,x2) => x0.wire__crate__api__memory_import__parse_memory_text(x1,x2),
      _2128: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_execute_command(x1,x2,x3),
      _2129: (x0,x1,x2) => x0.wire__crate__api__plugins__plugins_export_configs(x1,x2),
      _2130: (x0,x1,x2) => x0.wire__crate__api__plugins__plugins_get_config(x1,x2),
      _2131: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_import_configs(x1,x2,x3),
      _2132: (x0,x1,x2,x3,x4) => x0.wire__crate__api__plugins__plugins_init(x1,x2,x3,x4),
      _2133: (x0,x1) => x0.wire__crate__api__plugins__plugins_list(x1),
      _2134: (x0,x1) => x0.wire__crate__api__plugins__plugins_list_config_descriptors(x1),
      _2135: (x0,x1) => x0.wire__crate__api__plugins__plugins_load_configs_from_vault(x1),
      _2136: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_query_panel_data(x1,x2,x3),
      _2137: (x0,x1,x2) => x0.wire__crate__api__plugins__plugins_reindex(x1,x2),
      _2138: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_set_config(x1,x2,x3),
      _2139: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_set_enabled(x1,x2,x3),
      _2141: (x0,x1) => x0.wire__crate__api__plugins__plugins_sync_configs_to_vault(x1),
      _2144: (x0,x1,x2,x3) => x0.wire__crate__api__roadmap__process_roadmap_data(x1,x2,x3),
      _2172: (x0,x1,x2) => x0.wire__crate__api__sum_array(x1,x2),
      _2175: (x0,x1,x2,x3) => x0.wire__crate__api__typst__typst_compile_svg_pages(x1,x2,x3),
      _2176: (x0,x1,x2) => x0.wire__crate__api__typst__typst_engine_create(x1,x2),
      _2177: (x0,x1,x2) => x0.wire__crate__api__typst__typst_engine_dispose(x1,x2),
      _2178: (x0,x1,x2) => x0.wire__crate__api__typst__typst_highlight_tokens(x1,x2),
      _2192: (x0,x1,x2,x3,x4,x5) => x0.wire__crate__api__vector_store__types__vector_document_new(x1,x2,x3,x4,x5),
      _2199: (x0,x1,x2,x3) => x0.wire__crate__api__vector_store__vector_store_init(x1,x2,x3),
      _2200: (x0,x1) => x0.wire__crate__api__vector_store__vector_store_is_initialized(x1),
      _2201: (x0,x1,x2,x3) => x0.wire__crate__api__vector_store__vector_store_search(x1,x2,x3),
      _2204: (x0,x1,x2) => x0.wire__crate__api__vector_store__vector_store_upsert_batch(x1,x2),
      _2221: (x0,x1,x2) => x0.wire__crate__api__yns__parser__yns_parse(x1,x2),
      _2232: (x0,x1) => x0.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(x1),
      _2233: (x0,x1) => x0.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(x1),
      _2236: () => globalThis.wasm_bindgen,
      _2240: () => globalThis.wasm_bindgen.frb_get_rust_content_hash(),
      _2244: (x0,x1,x2) => x0.open(x1,x2),
      _2245: x0 => x0.abort(),
      _2246: x0 => x0.getAllResponseHeaders(),
      _2247: x0 => globalThis.wasm_bindgen(x0),
      _2248: (x0,x1) => x0.warn(x1),
      _2249: (x0,x1) => x0.item(x1),
      _2251: () => new AbortController(),
      _2252: x0 => x0.abort(),
      _2253: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _2254: (x0,x1) => globalThis.fetch(x0,x1),
      _2255: (x0,x1) => x0.get(x1),
      _2256: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._2256(f,arguments.length,x0,x1,x2) }),
      _2257: (x0,x1) => x0.forEach(x1),
      _2258: x0 => x0.getReader(),
      _2259: x0 => x0.cancel(),
      _2260: x0 => x0.read(),
      _2261: x0 => x0.trustedTypes,
      _2262: (x0,x1) => { x0.src = x1 },
      _2263: (x0,x1) => x0.createScriptURL(x1),
      _2264: x0 => x0.nonce,
      _2265: (x0,x1) => x0.debug(x1),
      _2266: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2266(f,arguments.length,x0) }),
      _2267: x0 => ({createScriptURL: x0}),
      _2268: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _2269: (x0,x1) => x0.querySelectorAll(x1),
      _2270: (x0,x1) => x0.createImageBitmap(x1),
      _2452: (x0,x1) => { x0.fillColor = x1 },
      _2491: o => o instanceof Array,
      _2492: (a, i) => a.push(i),
      _2493: (a, i) => a.splice(i, 1)[0],
      _2495: (a, l) => a.length = l,
      _2496: a => a.pop(),
      _2497: (a, i) => a.splice(i, 1),
      _2498: (a, s) => a.join(s),
      _2499: (a, s, e) => a.slice(s, e),
      _2500: (a, s, e) => a.splice(s, e),
      _2501: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _2502: a => a.length,
      _2503: (a, l) => a.length = l,
      _2504: (a, i) => a[i],
      _2505: (a, i, v) => a[i] = v,
      _2507: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof ArrayBuffer) return 1;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 2;
        }
        return 3;
      },
      _2508: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2509: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof DataView) return 1;
        return 2;
      },
      _2510: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Uint8Array) return 1;
        return 2;
      },
      _2511: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2512: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Int8Array) return 1;
        return 2;
      },
      _2513: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2514: o => o instanceof Uint8ClampedArray,
      _2515: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2516: o => o instanceof Uint16Array,
      _2517: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2518: o => o instanceof Int16Array,
      _2519: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2520: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Uint32Array) return 1;
        return 2;
      },
      _2521: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2522: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Int32Array) return 1;
        return 2;
      },
      _2523: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2525: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2526: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Float32Array) return 1;
        return 2;
      },
      _2527: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2528: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Float64Array) return 1;
        return 2;
      },
      _2529: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2530: (t, s) => t.set(s),
      _2531: l => new DataView(new ArrayBuffer(l)),
      _2532: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2533: o => o.byteLength,
      _2534: o => o.buffer,
      _2535: o => o.byteOffset,
      _2536: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2537: (b, o) => new DataView(b, o),
      _2538: (b, o, l) => new DataView(b, o, l),
      _2539: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2540: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2541: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2542: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2543: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2544: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2545: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2546: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2547: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2548: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2549: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2550: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2553: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2554: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2555: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2556: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2557: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2558: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2559: Function.prototype.call.bind(Number.prototype.toString),
      _2560: Function.prototype.call.bind(BigInt.prototype.toString),
      _2561: Function.prototype.call.bind(Number.prototype.toString),
      _2562: (d, digits) => d.toFixed(digits),
      _2569: (x0,x1,x2) => x0.toDataURL(x1,x2),
      _2573: x0 => new Function(x0),
      _2574: x0 => x0.call(),
      _2575: () => globalThis.crossOriginIsolated,
      _2576: x0 => globalThis.BigInt(x0),
      _2587: () => globalThis.document,
      _2588: () => globalThis.window,
      _2593: (x0,x1) => { x0.height = x1 },
      _2595: (x0,x1) => { x0.width = x1 },
      _2597: (x0,x1) => { x0.pointerEvents = x1 },
      _2600: x0 => x0.head,
      _2601: x0 => x0.classList,
      _2605: (x0,x1) => { x0.innerText = x1 },
      _2606: x0 => x0.style,
      _2608: x0 => x0.sheet,
      _2609: x0 => x0.src,
      _2610: (x0,x1) => { x0.src = x1 },
      _2611: x0 => x0.naturalWidth,
      _2612: x0 => x0.naturalHeight,
      _2619: x0 => x0.offsetX,
      _2620: x0 => x0.offsetY,
      _2621: x0 => x0.button,
      _2628: x0 => x0.status,
      _2629: (x0,x1) => { x0.responseType = x1 },
      _2631: x0 => x0.response,
      _2708: x0 => { globalThis.onGoogleLibraryLoad = x0 },
      _2709: (module,f) => finalizeWrapper(f, function() { return module.exports._2709(f,arguments.length) }),
      _2747: x0 => x0.readyState,
      _2749: (x0,x1) => { x0.timeout = x1 },
      _2751: (x0,x1) => { x0.withCredentials = x1 },
      _2752: x0 => x0.upload,
      _2753: x0 => x0.responseURL,
      _2754: x0 => x0.status,
      _2755: x0 => x0.statusText,
      _2757: (x0,x1) => { x0.responseType = x1 },
      _2758: x0 => x0.response,
      _2770: x0 => x0.loaded,
      _2771: x0 => x0.total,
      _2818: (x0,x1) => { x0.draggable = x1 },
      _2834: x0 => x0.style,
      _2847: (x0,x1) => { x0.oncancel = x1 },
      _2853: (x0,x1) => { x0.onchange = x1 },
      _2893: (x0,x1) => { x0.onerror = x1 },
      _3033: (x0,x1) => { x0.nonce = x1 },
      _3087: x0 => x0.content,
      _3193: (x0,x1) => { x0.download = x1 },
      _3218: (x0,x1) => { x0.href = x1 },
      _3266: (x0,x1) => { x0.src = x1 },
      _3311: (x0,x1) => { x0.src = x1 },
      _3760: (x0,x1) => { x0.accept = x1 },
      _3774: x0 => x0.files,
      _3800: (x0,x1) => { x0.multiple = x1 },
      _3818: (x0,x1) => { x0.type = x1 },
      _4067: x0 => x0.src,
      _4068: (x0,x1) => { x0.src = x1 },
      _4070: (x0,x1) => { x0.type = x1 },
      _4074: (x0,x1) => { x0.async = x1 },
      _4076: (x0,x1) => { x0.defer = x1 },
      _4088: (x0,x1) => { x0.charset = x1 },
      _4113: (x0,x1) => { x0.width = x1 },
      _4115: (x0,x1) => { x0.height = x1 },
      _4535: () => globalThis.window,
      _4575: x0 => x0.document,
      _4578: x0 => x0.location,
      _4597: x0 => x0.navigator,
      _4852: x0 => x0.isSecureContext,
      _4855: x0 => x0.crypto,
      _4859: x0 => x0.trustedTypes,
      _4860: x0 => x0.sessionStorage,
      _4861: x0 => x0.localStorage,
      _4869: x0 => x0.href,
      _4920: x0 => x0.message,
      _4962: x0 => x0.clipboard,
      _4964: x0 => x0.geolocation,
      _4967: x0 => x0.mediaDevices,
      _4969: x0 => x0.permissions,
      _4970: x0 => x0.maxTouchPoints,
      _4977: x0 => x0.appCodeName,
      _4978: x0 => x0.appName,
      _4979: x0 => x0.appVersion,
      _4980: x0 => x0.platform,
      _4981: x0 => x0.product,
      _4982: x0 => x0.productSub,
      _4983: x0 => x0.userAgent,
      _4984: x0 => x0.vendor,
      _4985: x0 => x0.vendorSub,
      _4987: x0 => x0.language,
      _4988: x0 => x0.languages,
      _4989: x0 => x0.onLine,
      _4994: x0 => x0.hardwareConcurrency,
      _4996: x0 => x0.storage,
      _5016: x0 => x0.width,
      _5017: x0 => x0.height,
      _5033: x0 => x0.data,
      _5034: x0 => x0.origin,
      _5063: x0 => x0.port1,
      _5064: x0 => x0.port2,
      _5066: (x0,x1) => { x0.onmessage = x1 },
      _5144: x0 => x0.port,
      _5179: x0 => x0.length,
      _7079: x0 => x0.type,
      _7080: x0 => x0.target,
      _7120: x0 => x0.signal,
      _7129: x0 => x0.length,
      _7131: x0 => x0.length,
      _7171: x0 => x0.baseURI,
      _7177: x0 => x0.firstChild,
      _7188: () => globalThis.document,
      _7269: x0 => x0.body,
      _7271: x0 => x0.head,
      _7600: (x0,x1) => { x0.id = x1 },
      _7627: x0 => x0.children,
      _8946: x0 => x0.value,
      _8948: x0 => x0.done,
      _9107: x0 => x0.size,
      _9108: x0 => x0.type,
      _9111: (x0,x1) => { x0.type = x1 },
      _9114: x0 => x0.name,
      _9115: x0 => x0.lastModified,
      _9120: x0 => x0.length,
      _9125: x0 => x0.result,
      _9621: x0 => x0.url,
      _9623: x0 => x0.status,
      _9625: x0 => x0.statusText,
      _9626: x0 => x0.headers,
      _9627: x0 => x0.body,
      _11074: x0 => x0.result,
      _11075: x0 => x0.error,
      _11086: (x0,x1) => { x0.onupgradeneeded = x1 },
      _11088: x0 => x0.oldVersion,
      _11167: x0 => x0.key,
      _11168: x0 => x0.primaryKey,
      _11170: x0 => x0.value,
      _12008: (x0,x1) => { x0.display = x1 },
      _12172: (x0,x1) => { x0.height = x1 },
      _12344: (x0,x1) => { x0.maxWidth = x1 },
      _12862: (x0,x1) => { x0.width = x1 },
      _13230: x0 => x0.name,
      _13231: x0 => x0.message,
      _13234: x0 => x0.subtle,
      _13938: () => globalThis.console,
      _13964: () => globalThis.speechSynthesis,
      _13965: (x0,x1) => { x0.lang = x1 },
      _13967: (x0,x1) => { x0.pitch = x1 },
      _13970: (x0,x1) => { x0.rate = x1 },
      _13972: (x0,x1) => { x0.text = x1 },
      _13973: (x0,x1) => { x0.voice = x1 },
      _13974: x0 => x0.voice,
      _13976: (x0,x1) => { x0.volume = x1 },
      _13977: (x0,x1) => { x0.onstart = x1 },
      _13978: (x0,x1) => { x0.onend = x1 },
      _13979: (x0,x1) => { x0.onpause = x1 },
      _13980: (x0,x1) => { x0.onresume = x1 },
      _13981: (x0,x1) => { x0.onerror = x1 },
      _13982: (x0,x1) => { x0.onboundary = x1 },
      _13984: x0 => x0.lang,
      _13985: x0 => x0.localService,
      _13986: x0 => x0.name,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      s: [
        "([ \r\n\t]+)|([!-\\[\\]-‧‪-퟿豈-￿][̀-ͯ]*|[\ud800-\udbff][\udc00-\udfff][̀-ͯ]*|\\\\verb\\*([^]).*?\\3|\\\\verb([^*a-zA-Z]).*?\\4|\\\\operatorname\\*|\\\\[a-zA-Z@]+[ \r\n\t]*|\\\\[^\ud800-\udfff])",
      ],
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
