// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _17: (x0,x1) => x0.get(x1),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _754: x0 => x0.baseURI,
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _919: x0 => x0.headers,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1283: (x0,x1) => x0.createElement(x1),
      _1284: (x0,x1) => x0.querySelector(x1),
      _1285: (x0,x1) => x0.appendChild(x1),
      _1286: x0 => ({type: x0}),
      _1287: (x0,x1) => new Blob(x0,x1),
      _1288: x0 => globalThis.URL.createObjectURL(x0),
      _1290: (x0,x1,x2,x3) => x0.sendCommand(x1,x2,x3),
      _1291: () => globalThis.PdfiumWasmCommunicator,
      _1293: x0 => { globalThis.pdfiumWasmWorkerUrl = x0 },
      _1294: (x0,x1) => x0.writeText(x1),
      _1295: x0 => x0.preventDefault(),
      _1296: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1296(f,arguments.length,x0) }),
      _1297: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1305: x0 => x0.createRange(),
      _1306: (x0,x1) => x0.selectNode(x1),
      _1307: x0 => x0.getSelection(),
      _1308: x0 => x0.removeAllRanges(),
      _1309: (x0,x1) => x0.addRange(x1),
      _1310: (x0,x1) => x0.createElement(x1),
      _1311: (x0,x1) => x0.append(x1),
      _1312: (x0,x1,x2) => x0.insertRule(x1,x2),
      _1313: (x0,x1) => x0.add(x1),
      _1314: x0 => x0.preventDefault(),
      _1315: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1315(f,arguments.length,x0) }),
      _1316: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1317: () => globalThis.window.navigator.userAgent,
      _1318: (x0,x1) => x0.append(x1),
      _1319: x0 => x0.remove(),
      _1320: (x0,x1) => x0.removeItem(x1),
      _1321: (x0,x1) => x0.getItem(x1),
      _1322: x0 => globalThis.URL.revokeObjectURL(x0),
      _1324: (x0,x1,x2,x3,x4,x5) => x0.drawImage(x1,x2,x3,x4,x5),
      _1327: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1327(f,arguments.length,x0) }),
      _1328: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1328(f,arguments.length,x0) }),
      _1329: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1329(f,arguments.length,x0) }),
      _1330: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1331: (x0,x1) => x0.replaceChildren(x1),
      _1332: x0 => x0.click(),
      _1333: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24) => ({aspectRatio: x0,background: x1,center: x2,checkCrossOrigin: x3,checkOrientation: x4,cropBoxMovable: x5,cropBoxResizable: x6,dragMode: x7,guides: x8,highlight: x9,initialAspectRatio: x10,minContainerHeight: x11,minContainerWidth: x12,minCropBoxHeight: x13,minCropBoxWidth: x14,modal: x15,movable: x16,rotatable: x17,scalable: x18,toggleDragModeOnDblclick: x19,viewMode: x20,wheelZoomRatio: x21,zoomOnTouch: x22,zoomOnWheel: x23,zoomable: x24}),
      _1334: (x0,x1) => new Cropper(x0,x1),
      _1335: () => ({}),
      _1336: (x0,x1) => x0.getCroppedCanvas(x1),
      _1337: x0 => x0.getCroppedCanvas(),
      _1338: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1338(f,arguments.length,x0) }),
      _1339: (x0,x1,x2) => x0.toBlob(x1,x2),
      _1340: (x0,x1) => x0.rotate(x1),
      _1341: (x0,x1) => x0.scale(x1),
      _1342: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1343: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1345: (x0,x1) => x0.getAttribute(x1),
      _1349: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1350: (x0,x1) => x0.canShare(x1),
      _1351: (x0,x1) => x0.share(x1),
      _1353: (x0,x1,x2) => ({files: x0,title: x1,text: x2}),
      _1354: (x0,x1) => ({files: x0,text: x1}),
      _1355: (x0,x1) => ({files: x0,title: x1}),
      _1356: x0 => ({files: x0}),
      _1357: (x0,x1) => ({title: x0,text: x1}),
      _1359: () => ({}),
      _1360: (x0,x1,x2) => new File(x0,x1,x2),
      _1370: (x0,x1) => x0.item(x1),
      _1371: x0 => x0.decode(),
      _1372: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1373: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1374: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1374(f,arguments.length,x0) }),
      _1375: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1375(f,arguments.length,x0) }),
      _1376: x0 => x0.send(),
      _1377: () => new XMLHttpRequest(),
      _1378: (x0,x1) => x0.key(x1),
      _1379: (x0,x1,x2) => x0.setItem(x1,x2),
      _1393: (x0,x1) => x0.item(x1),
      _1394: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1394(f,arguments.length,x0) }),
      _1409: (x0,x1) => x0.getContext(x1),
      _1410: (x0,x1,x2,x3,x4) => x0.clearRect(x1,x2,x3,x4),
      _1411: x0 => x0.close(),
      _1412: () => new FileReader(),
      _1414: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1415: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1415(f,arguments.length,x0) }),
      _1416: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1417: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1417(f,arguments.length,x0) }),
      _1418: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1418(f,arguments.length,x0) }),
      _1419: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1419(f,arguments.length,x0) }),
      _1420: (x0,x1) => x0.removeChild(x1),
      _1421: x0 => new Blob(x0),
      _1423: x0 => x0.deviceMemory,
      _1424: () => new SpeechSynthesisUtterance(),
      _1425: x0 => x0.pause(),
      _1426: x0 => x0.resume(),
      _1427: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1427(f,arguments.length,x0) }),
      _1428: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1428(f,arguments.length,x0) }),
      _1429: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1429(f,arguments.length,x0) }),
      _1430: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1430(f,arguments.length,x0) }),
      _1431: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1431(f,arguments.length,x0) }),
      _1432: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1432(f,arguments.length,x0) }),
      _1433: (x0,x1) => x0.speak(x1),
      _1434: x0 => x0.cancel(),
      _1435: x0 => x0.getVoices(),
      _1436: () => globalThis.Intl.DateTimeFormat(),
      _1437: x0 => x0.resolvedOptions(),
      _1438: x0 => globalThis.Intl.supportedValuesOf(x0),
      _1439: x0 => x0.timeZone,
      _1440: (x0,x1,x2,x3,x4,x5,x6,x7) => x0.unwrapKey(x1,x2,x3,x4,x5,x6,x7),
      _1441: (x0,x1,x2,x3,x4,x5) => x0.importKey(x1,x2,x3,x4,x5),
      _1442: (x0,x1,x2,x3) => x0.generateKey(x1,x2,x3),
      _1443: (x0,x1,x2,x3,x4) => x0.wrapKey(x1,x2,x3,x4),
      _1444: (x0,x1,x2) => x0.exportKey(x1,x2),
      _1445: (x0,x1) => x0.getRandomValues(x1),
      _1446: (x0,x1,x2,x3) => x0.encrypt(x1,x2,x3),
      _1447: (x0,x1,x2,x3) => x0.decrypt(x1,x2,x3),
      _1458: Date.now,
      _1460: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1461: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1462: () => new Error().stack,
      _1463: () => typeof dartUseDateNowForTicks !== "undefined",
      _1464: () => 1000 * performance.now(),
      _1465: () => Date.now(),
      _1466: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1467: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1468: () => new WeakMap(),
      _1469: (map, o) => map.get(o),
      _1470: (map, o, v) => map.set(o, v),
      _1471: (exn) => exn.toString(),
      _1472: (exn) => exn.stack,
      _1473: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1474: x0 => new WeakRef(x0),
      _1475: x0 => x0.deref(),
      _1476: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1476(f,arguments.length,x0) }),
      _1477: x0 => new FinalizationRegistry(x0),
      _1478: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _1480: (x0,x1) => x0.unregister(x1),
      _1482: () => globalThis.WeakRef,
      _1483: () => globalThis.FinalizationRegistry,
      _1485: x0 => x0.call(),
      _1486: s => JSON.stringify(s),
      _1487: s => printToConsole(s),
      _1488: (o, p, r) => o.replaceAll(p, () => r),
      _1489: (o, p, r) => o.replace(p, () => r),
      _1490: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1491: s => s.toUpperCase(),
      _1492: s => s.trim(),
      _1493: s => s.trimLeft(),
      _1494: s => s.trimRight(),
      _1495: (string, times) => string.repeat(times),
      _1496: Function.prototype.call.bind(String.prototype.indexOf),
      _1497: (s, p, i) => s.lastIndexOf(p, i),
      _1498: (string, token) => string.split(token),
      _1499: Object.is,
      _1502: (o, t) => typeof o === t,
      _1503: (o, c) => o instanceof c,
      _1504: o => Object.keys(o),
      _1507: (o, a) => o + a,
      _1517: (o, a) => o == a,
      _1534: x0 => new Array(x0),
      _1536: x0 => x0.length,
      _1538: (x0,x1) => x0[x1],
      _1539: (x0,x1,x2) => { x0[x1] = x2 },
      _1542: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1544: x0 => new Int8Array(x0),
      _1545: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1547: x0 => new Uint8ClampedArray(x0),
      _1549: x0 => new Int16Array(x0),
      _1551: x0 => new Uint16Array(x0),
      _1553: x0 => new Int32Array(x0),
      _1555: x0 => new Uint32Array(x0),
      _1557: x0 => new Float32Array(x0),
      _1559: x0 => new Float64Array(x0),
      _1580: (x0,x1) => x0.call(x1),
      _1583: x0 => x0.random(),
      _1584: (x0,x1) => x0.getRandomValues(x1),
      _1585: () => globalThis.crypto,
      _1586: () => globalThis.Math,
      _1588: () => globalThis.performance,
      _1589: () => globalThis.JSON,
      _1590: x0 => x0.measure,
      _1591: x0 => x0.mark,
      _1592: x0 => x0.clearMeasures,
      _1593: x0 => x0.clearMarks,
      _1594: (x0,x1,x2,x3) => x0.measure(x1,x2,x3),
      _1595: (x0,x1,x2) => x0.mark(x1,x2),
      _1596: x0 => x0.clearMeasures(),
      _1597: x0 => x0.clearMarks(),
      _1598: (x0,x1) => x0.parse(x1),
      _1599: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1600: (handle) => clearTimeout(handle),
      _1601: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1602: (handle) => clearInterval(handle),
      _1603: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1604: () => Date.now(),
      _1605: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1606: (x0,x1) => x0.exec(x1),
      _1607: (x0,x1) => x0.test(x1),
      _1608: x0 => x0.pop(),
      _1610: o => o === undefined,
      _1612: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1614: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1615: o => o instanceof RegExp,
      _1616: (l, r) => l === r,
      _1617: o => o,
      _1618: o => o,
      _1619: o => o,
      _1620: b => !!b,
      _1621: o => o.length,
      _1623: (o, i) => o[i],
      _1624: f => f.dartFunction,
      _1625: () => ({}),
      _1626: () => [],
      _1628: () => globalThis,
      _1629: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1630: (o, p) => p in o,
      _1631: (o, p) => o[p],
      _1632: (o, p, v) => o[p] = v,
      _1633: (o, m, a) => o[m].apply(o, a),
      _1635: o => String(o),
      _1636: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1637: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1637(f,arguments.length,x0) }),
      _1638: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1638(f,arguments.length,x0,x1) }),
      _1639: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1640: o => [o],
      _1641: (o0, o1) => [o0, o1],
      _1642: (o0, o1, o2) => [o0, o1, o2],
      _1643: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1644: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1645: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1646: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1647: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1648: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1649: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1650: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1651: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1652: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1653: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1654: x0 => new ArrayBuffer(x0),
      _1655: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1656: x0 => x0.input,
      _1657: x0 => x0.index,
      _1658: x0 => x0.groups,
      _1659: x0 => x0.flags,
      _1660: x0 => x0.multiline,
      _1661: x0 => x0.ignoreCase,
      _1662: x0 => x0.unicode,
      _1663: x0 => x0.dotAll,
      _1664: (x0,x1) => { x0.lastIndex = x1 },
      _1665: (o, p) => p in o,
      _1666: (o, p) => o[p],
      _1667: (o, p, v) => o[p] = v,
      _1669: x0 => x0.exports,
      _1670: (x0,x1) => globalThis.WebAssembly.instantiateStreaming(x0,x1),
      _1671: x0 => x0.instance,
      _1673: x0 => new WebAssembly.Memory(x0),
      _1674: x0 => x0.buffer,
      _1677: x0 => x0.arrayBuffer(),
      _1679: x0 => x0.sqlite3_initialize,
      _1681: (x0,x1,x2,x3,x4) => x0.sqlite3_open_v2(x1,x2,x3,x4),
      _1682: (x0,x1) => x0.sqlite3_close_v2(x1),
      _1683: (x0,x1,x2) => x0.sqlite3_extended_result_codes(x1,x2),
      _1684: (x0,x1) => x0.sqlite3_extended_errcode(x1),
      _1685: (x0,x1) => x0.sqlite3_errmsg(x1),
      _1686: (x0,x1) => x0.sqlite3_errstr(x1),
      _1687: x0 => x0.sqlite3_error_offset,
      _1691: (x0,x1) => x0.sqlite3_last_insert_rowid(x1),
      _1692: (x0,x1) => x0.sqlite3_changes(x1),
      _1693: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_exec(x1,x2,x3,x4,x5),
      _1696: (x0,x1,x2,x3,x4,x5,x6) => x0.sqlite3_prepare_v3(x1,x2,x3,x4,x5,x6),
      _1697: (x0,x1) => x0.sqlite3_finalize(x1),
      _1698: (x0,x1) => x0.sqlite3_step(x1),
      _1699: (x0,x1) => x0.sqlite3_reset(x1),
      _1700: (x0,x1) => x0.sqlite3_stmt_isexplain(x1),
      _1702: (x0,x1) => x0.sqlite3_column_count(x1),
      _1703: (x0,x1) => x0.sqlite3_bind_parameter_count(x1),
      _1705: (x0,x1,x2) => x0.sqlite3_column_name(x1,x2),
      _1706: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_bind_blob64(x1,x2,x3,x4,x5),
      _1707: (x0,x1,x2,x3) => x0.sqlite3_bind_double(x1,x2,x3),
      _1708: (x0,x1,x2,x3) => x0.sqlite3_bind_int64(x1,x2,x3),
      _1709: (x0,x1,x2) => x0.sqlite3_bind_null(x1,x2),
      _1710: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_bind_text(x1,x2,x3,x4,x5),
      _1711: (x0,x1,x2) => x0.sqlite3_column_blob(x1,x2),
      _1712: (x0,x1,x2) => x0.sqlite3_column_double(x1,x2),
      _1713: (x0,x1,x2) => x0.sqlite3_column_int64(x1,x2),
      _1714: (x0,x1,x2) => x0.sqlite3_column_text(x1,x2),
      _1715: (x0,x1,x2) => x0.sqlite3_column_bytes(x1,x2),
      _1716: (x0,x1,x2) => x0.sqlite3_column_type(x1,x2),
      _1717: (x0,x1) => x0.sqlite3_value_blob(x1),
      _1718: (x0,x1) => x0.sqlite3_value_double(x1),
      _1719: (x0,x1) => x0.sqlite3_value_type(x1),
      _1720: (x0,x1) => x0.sqlite3_value_int64(x1),
      _1721: (x0,x1) => x0.sqlite3_value_text(x1),
      _1722: (x0,x1) => x0.sqlite3_value_bytes(x1),
      _1725: (x0,x1) => x0.sqlite3_user_data(x1),
      _1726: (x0,x1,x2,x3,x4) => x0.sqlite3_result_blob64(x1,x2,x3,x4),
      _1727: (x0,x1,x2) => x0.sqlite3_result_double(x1,x2),
      _1728: (x0,x1,x2,x3) => x0.sqlite3_result_error(x1,x2,x3),
      _1729: (x0,x1,x2) => x0.sqlite3_result_int64(x1,x2),
      _1730: (x0,x1) => x0.sqlite3_result_null(x1),
      _1731: (x0,x1,x2,x3,x4) => x0.sqlite3_result_text(x1,x2,x3,x4),
      _1732: x0 => x0.sqlite3_result_subtype,
      _1751: (x0,x1) => x0.dart_sqlite3_malloc(x1),
      _1752: (x0,x1) => x0.dart_sqlite3_free(x1),
      _1753: (x0,x1,x2,x3) => x0.dart_sqlite3_register_vfs(x1,x2,x3),
      _1754: (x0,x1,x2,x3,x4,x5) => x0.dart_sqlite3_create_scalar_function(x1,x2,x3,x4,x5),
      _1757: x0 => x0.dart_sqlite3_updates,
      _1758: x0 => x0.dart_sqlite3_commits,
      _1759: x0 => x0.dart_sqlite3_rollbacks,
      _1763: x0 => ({initial: x0}),
      _1764: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1764(f,arguments.length,x0) }),
      _1765: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1765(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1766: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1766(f,arguments.length,x0,x1,x2) }),
      _1767: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1767(f,arguments.length,x0,x1,x2,x3) }),
      _1768: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1768(f,arguments.length,x0,x1,x2,x3) }),
      _1769: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1769(f,arguments.length,x0,x1,x2) }),
      _1770: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1770(f,arguments.length,x0,x1) }),
      _1771: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1771(f,arguments.length,x0,x1) }),
      _1772: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1772(f,arguments.length,x0) }),
      _1773: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1773(f,arguments.length,x0) }),
      _1774: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1774(f,arguments.length,x0,x1,x2,x3) }),
      _1775: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return module.exports._1775(f,arguments.length,x0,x1,x2,x3) }),
      _1776: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1776(f,arguments.length,x0,x1) }),
      _1777: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1777(f,arguments.length,x0,x1) }),
      _1778: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1778(f,arguments.length,x0,x1) }),
      _1779: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1779(f,arguments.length,x0,x1) }),
      _1780: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1780(f,arguments.length,x0,x1) }),
      _1781: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1781(f,arguments.length,x0,x1) }),
      _1782: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1782(f,arguments.length,x0,x1,x2) }),
      _1783: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1783(f,arguments.length,x0,x1,x2) }),
      _1784: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1784(f,arguments.length,x0,x1,x2) }),
      _1785: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1785(f,arguments.length,x0) }),
      _1786: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1786(f,arguments.length,x0) }),
      _1787: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1787(f,arguments.length,x0) }),
      _1788: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1788(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1789: (module,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return module.exports._1789(f,arguments.length,x0,x1,x2,x3,x4) }),
      _1790: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1790(f,arguments.length,x0) }),
      _1791: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1791(f,arguments.length,x0) }),
      _1792: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1792(f,arguments.length,x0,x1) }),
      _1793: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1793(f,arguments.length,x0,x1) }),
      _1794: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1794(f,arguments.length,x0,x1,x2) }),
      _1796: (x0,x1,x2,x3) => x0.call(x1,x2,x3),
      _1801: x0 => new URL(x0),
      _1802: (x0,x1) => new URL(x0,x1),
      _1803: (x0,x1) => globalThis.fetch(x0,x1),
      _1804: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1805: (x0,x1,x2) => x0.postMessage(x1,x2),
      _1807: (x0,x1) => ({i: x0,p: x1}),
      _1808: (x0,x1) => ({c: x0,r: x1}),
      _1809: x0 => x0.i,
      _1810: x0 => x0.p,
      _1811: x0 => x0.c,
      _1812: x0 => x0.r,
      _1813: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1813(f,arguments.length,x0) }),
      _1814: (x0,x1) => x0.postMessage(x1),
      _1815: x0 => x0.close(),
      _1817: x0 => new Worker(x0),
      _1819: x0 => x0.getDirectory(),
      _1820: x0 => ({create: x0}),
      _1821: (x0,x1,x2) => x0.getFileHandle(x1,x2),
      _1822: x0 => x0.createSyncAccessHandle(),
      _1823: x0 => x0.close(),
      _1826: x0 => x0.close(),
      _1829: (x0,x1,x2) => x0.open(x1,x2),
      _1833: (x0,x1,x2) => x0.getDirectoryHandle(x1,x2),
      _1838: x0 => ({create: x0}),
      _1843: (x0,x1) => new SharedWorker(x0,x1),
      _1844: x0 => x0.start(),
      _1845: x0 => x0.terminate(),
      _1846: () => new MessageChannel(),
      _1850: x0 => new SharedArrayBuffer(x0),
      _1851: x0 => ({at: x0}),
      _1852: x0 => x0.getSize(),
      _1853: (x0,x1) => x0.truncate(x1),
      _1854: x0 => x0.flush(),
      _1857: x0 => x0.synchronizationBuffer,
      _1858: x0 => x0.communicationBuffer,
      _1859: (x0,x1,x2,x3) => ({clientVersion: x0,root: x1,synchronizationBuffer: x2,communicationBuffer: x3}),
      _1860: (x0,x1) => globalThis.IDBKeyRange.bound(x0,x1),
      _1861: x0 => ({autoIncrement: x0}),
      _1862: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      _1863: x0 => ({unique: x0}),
      _1864: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      _1865: (x0,x1) => x0.createObjectStore(x1),
      _1866: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1866(f,arguments.length,x0) }),
      _1867: (x0,x1,x2) => x0.transaction(x1,x2),
      _1868: (x0,x1) => x0.objectStore(x1),
      _1870: (x0,x1) => x0.index(x1),
      _1871: x0 => x0.openKeyCursor(),
      _1872: (x0,x1) => x0.getKey(x1),
      _1873: (x0,x1) => ({name: x0,length: x1}),
      _1874: (x0,x1) => x0.put(x1),
      _1875: (x0,x1) => x0.get(x1),
      _1876: (x0,x1) => x0.openCursor(x1),
      _1877: x0 => globalThis.IDBKeyRange.only(x0),
      _1878: (x0,x1,x2) => x0.put(x1,x2),
      _1879: (x0,x1) => x0.update(x1),
      _1880: (x0,x1) => x0.delete(x1),
      _1881: x0 => x0.name,
      _1882: x0 => x0.length,
      _1885: x0 => x0.continue(),
      _1886: () => globalThis.indexedDB,
      _1887: () => globalThis.navigator,
      _1888: (x0,x1) => x0.read(x1),
      _1889: (x0,x1,x2) => x0.read(x1,x2),
      _1890: (x0,x1) => x0.write(x1),
      _1891: (x0,x1,x2) => x0.write(x1,x2),
      _1893: (x0,x1,x2) => globalThis.Atomics.wait(x0,x1,x2),
      _1895: (x0,x1,x2) => globalThis.Atomics.notify(x0,x1,x2),
      _1896: (x0,x1,x2) => globalThis.Atomics.store(x0,x1,x2),
      _1897: (x0,x1) => globalThis.Atomics.load(x0,x1),
      _1898: () => globalThis.Int32Array,
      _1900: () => globalThis.Uint8Array,
      _1902: () => globalThis.DataView,
      _1904: x0 => x0.byteLength,
      _1906: x0 => globalThis.BigInt(x0),
      _1907: x0 => globalThis.Number(x0),
      _1914: x0 => new BroadcastChannel(x0),
      _1915: x0 => globalThis.Array.isArray(x0),
      _1916: (x0,x1) => x0.postMessage(x1),
      _1918: (x0,x1) => ({kind: x0,table: x1}),
      _1919: x0 => x0.kind,
      _1920: x0 => x0.table,
      _1921: () => new XMLHttpRequest(),
      _1922: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1924: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1925: (x0,x1) => x0.send(x1),
      _1926: x0 => x0.send(),
      _1928: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1928(f,arguments.length,x0) }),
      _1929: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1929(f,arguments.length,x0) }),
      _1963: (x0,x1,x2) => x0.wire__crate__api__pdf__extractor__analyze_pdf_pages(x1,x2),
      _1993: (x0,x1,x2) => x0.wire__crate__api__count_words(x1,x2),
      _2000: (x0,x1,x2,x3) => x0.wire__crate__api__security__decrypt(x1,x2,x3),
      _2005: (x0,x1,x2,x3) => x0.wire__crate__api__security__derive_key(x1,x2,x3),
      _2012: (x0,x1,x2) => x0.wire__crate__api__embeddings__embeddings_init(x1,x2),
      _2015: (x0,x1,x2,x3) => x0.wire__crate__api__security__encrypt(x1,x2,x3),
      _2029: (x0,x1,x2) => x0.wire__crate__api__pdf__extractor__extract_document_spans(x1,x2),
      _2033: (x0,x1,x2) => x0.wire__crate__api__fibonacci(x1,x2),
      _2042: (x0,x1,x2) => x0.wire__crate__api__embeddings__generate_embedding(x1,x2),
      _2044: (x0,x1,x2) => x0.wire__crate__api__generate_id(x1,x2),
      _2047: (x0,x1) => x0.wire__crate__api__security__generate_salt(x1),
      _2060: (x0,x1,x2) => x0.wire__crate__api__markdown__get_markdown_chunk_count(x1,x2),
      _2072: (x0,x1,x2) => x0.wire__crate__api__graph__graph_compute_depths(x1,x2),
      _2073: (x0,x1,x2,x3) => x0.wire__crate__api__graph__graph_create(x1,x2,x3),
      _2074: (x0,x1) => x0.wire__crate__api__graph__graph_destroy(x1),
      _2075: (x0,x1) => x0.wire__crate__api__graph__graph_get_edges(x1),
      _2076: (x0,x1) => x0.wire__crate__api__graph__graph_get_nodes(x1),
      _2078: (x0,x1,x2) => x0.wire__crate__api__graph__graph_simulate(x1,x2),
      _2079: (x0,x1) => x0.wire__crate__api__graph__graph_tick(x1),
      _2080: (x0,x1,x2) => x0.wire__crate__api__greet(x1,x2),
      _2089: (x0,x1,x2) => x0.wire__crate__api__is_prime(x1,x2),
      _2110: (x0,x1,x2,x3) => x0.wire__crate__api__markdown__parse_markdown_chunk(x1,x2,x3),
      _2111: (x0,x1,x2) => x0.wire__crate__api__markdown__parse_markdown_full(x1,x2),
      _2114: (x0,x1,x2) => x0.wire__crate__api__memory_import__parse_memory_anki(x1,x2),
      _2115: (x0,x1,x2) => x0.wire__crate__api__memory_import__parse_memory_json(x1,x2),
      _2116: (x0,x1,x2) => x0.wire__crate__api__memory_import__parse_memory_text(x1,x2),
      _2121: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_execute_command(x1,x2,x3),
      _2122: (x0,x1,x2) => x0.wire__crate__api__plugins__plugins_export_configs(x1,x2),
      _2123: (x0,x1,x2) => x0.wire__crate__api__plugins__plugins_get_config(x1,x2),
      _2124: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_import_configs(x1,x2,x3),
      _2125: (x0,x1,x2,x3,x4) => x0.wire__crate__api__plugins__plugins_init(x1,x2,x3,x4),
      _2126: (x0,x1) => x0.wire__crate__api__plugins__plugins_list(x1),
      _2127: (x0,x1) => x0.wire__crate__api__plugins__plugins_list_config_descriptors(x1),
      _2128: (x0,x1) => x0.wire__crate__api__plugins__plugins_load_configs_from_vault(x1),
      _2129: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_query_panel_data(x1,x2,x3),
      _2130: (x0,x1,x2) => x0.wire__crate__api__plugins__plugins_reindex(x1,x2),
      _2131: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_set_config(x1,x2,x3),
      _2132: (x0,x1,x2,x3) => x0.wire__crate__api__plugins__plugins_set_enabled(x1,x2,x3),
      _2134: (x0,x1) => x0.wire__crate__api__plugins__plugins_sync_configs_to_vault(x1),
      _2137: (x0,x1,x2,x3) => x0.wire__crate__api__roadmap__process_roadmap_data(x1,x2,x3),
      _2165: (x0,x1,x2) => x0.wire__crate__api__sum_array(x1,x2),
      _2168: (x0,x1,x2,x3) => x0.wire__crate__api__typst__typst_compile_svg_pages(x1,x2,x3),
      _2169: (x0,x1,x2) => x0.wire__crate__api__typst__typst_engine_create(x1,x2),
      _2170: (x0,x1,x2) => x0.wire__crate__api__typst__typst_engine_dispose(x1,x2),
      _2171: (x0,x1,x2) => x0.wire__crate__api__typst__typst_highlight_tokens(x1,x2),
      _2185: (x0,x1,x2,x3,x4,x5) => x0.wire__crate__api__vector_store__types__vector_document_new(x1,x2,x3,x4,x5),
      _2192: (x0,x1,x2,x3) => x0.wire__crate__api__vector_store__vector_store_init(x1,x2,x3),
      _2193: (x0,x1) => x0.wire__crate__api__vector_store__vector_store_is_initialized(x1),
      _2194: (x0,x1,x2,x3) => x0.wire__crate__api__vector_store__vector_store_search(x1,x2,x3),
      _2197: (x0,x1,x2) => x0.wire__crate__api__vector_store__vector_store_upsert_batch(x1,x2),
      _2214: (x0,x1,x2) => x0.wire__crate__api__yns__parser__yns_parse(x1,x2),
      _2225: (x0,x1) => x0.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(x1),
      _2226: (x0,x1) => x0.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTypstEngine(x1),
      _2229: () => globalThis.wasm_bindgen,
      _2233: () => globalThis.wasm_bindgen.frb_get_rust_content_hash(),
      _2237: (x0,x1,x2) => x0.open(x1,x2),
      _2238: x0 => x0.abort(),
      _2239: x0 => x0.getAllResponseHeaders(),
      _2240: x0 => globalThis.wasm_bindgen(x0),
      _2241: (x0,x1) => x0.warn(x1),
      _2244: () => new AbortController(),
      _2245: x0 => x0.abort(),
      _2246: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _2247: (x0,x1) => globalThis.fetch(x0,x1),
      _2248: (x0,x1) => x0.get(x1),
      _2249: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._2249(f,arguments.length,x0,x1,x2) }),
      _2250: (x0,x1) => x0.forEach(x1),
      _2251: x0 => x0.getReader(),
      _2252: x0 => x0.cancel(),
      _2253: x0 => x0.read(),
      _2254: x0 => x0.trustedTypes,
      _2255: (x0,x1) => { x0.src = x1 },
      _2256: (x0,x1) => x0.createScriptURL(x1),
      _2257: x0 => x0.nonce,
      _2258: (x0,x1) => x0.debug(x1),
      _2259: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2259(f,arguments.length,x0) }),
      _2260: x0 => ({createScriptURL: x0}),
      _2261: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _2262: (x0,x1) => x0.querySelectorAll(x1),
      _2263: (x0,x1) => x0.createImageBitmap(x1),
      _2445: (x0,x1) => { x0.fillColor = x1 },
      _2484: o => o instanceof Array,
      _2485: (a, i) => a.push(i),
      _2486: (a, i) => a.splice(i, 1)[0],
      _2488: (a, l) => a.length = l,
      _2489: a => a.pop(),
      _2490: (a, i) => a.splice(i, 1),
      _2491: (a, s) => a.join(s),
      _2492: (a, s, e) => a.slice(s, e),
      _2493: (a, s, e) => a.splice(s, e),
      _2494: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _2495: a => a.length,
      _2496: (a, l) => a.length = l,
      _2497: (a, i) => a[i],
      _2498: (a, i, v) => a[i] = v,
      _2500: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _2501: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2502: o => o instanceof DataView,
      _2503: o => o instanceof Uint8Array,
      _2504: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2505: o => o instanceof Int8Array,
      _2506: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2507: o => o instanceof Uint8ClampedArray,
      _2508: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2509: o => o instanceof Uint16Array,
      _2510: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2511: o => o instanceof Int16Array,
      _2512: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2513: o => o instanceof Uint32Array,
      _2514: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2515: o => o instanceof Int32Array,
      _2516: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2518: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2519: o => o instanceof Float32Array,
      _2520: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2521: o => o instanceof Float64Array,
      _2522: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2523: (t, s) => t.set(s),
      _2524: l => new DataView(new ArrayBuffer(l)),
      _2525: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2526: o => o.byteLength,
      _2527: o => o.buffer,
      _2528: o => o.byteOffset,
      _2529: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2530: (b, o) => new DataView(b, o),
      _2531: (b, o, l) => new DataView(b, o, l),
      _2532: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2533: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2534: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2535: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2536: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2537: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2538: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2539: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2540: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2541: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2542: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2543: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2546: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2547: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2548: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2549: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2550: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2551: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2552: Function.prototype.call.bind(Number.prototype.toString),
      _2553: Function.prototype.call.bind(BigInt.prototype.toString),
      _2554: Function.prototype.call.bind(Number.prototype.toString),
      _2555: (d, digits) => d.toFixed(digits),
      _2562: (x0,x1,x2) => x0.toDataURL(x1,x2),
      _2566: x0 => new Function(x0),
      _2567: x0 => x0.call(),
      _2568: () => globalThis.crossOriginIsolated,
      _2569: x0 => globalThis.BigInt(x0),
      _2580: () => globalThis.document,
      _2581: () => globalThis.window,
      _2586: (x0,x1) => { x0.height = x1 },
      _2588: (x0,x1) => { x0.width = x1 },
      _2590: (x0,x1) => { x0.pointerEvents = x1 },
      _2593: x0 => x0.head,
      _2594: x0 => x0.classList,
      _2598: (x0,x1) => { x0.innerText = x1 },
      _2599: x0 => x0.style,
      _2601: x0 => x0.sheet,
      _2602: x0 => x0.src,
      _2603: (x0,x1) => { x0.src = x1 },
      _2604: x0 => x0.naturalWidth,
      _2605: x0 => x0.naturalHeight,
      _2612: x0 => x0.offsetX,
      _2613: x0 => x0.offsetY,
      _2614: x0 => x0.button,
      _2621: x0 => x0.status,
      _2622: (x0,x1) => { x0.responseType = x1 },
      _2624: x0 => x0.response,
      _2701: x0 => { globalThis.onGoogleLibraryLoad = x0 },
      _2702: (module,f) => finalizeWrapper(f, function() { return module.exports._2702(f,arguments.length) }),
      _2740: x0 => x0.readyState,
      _2742: (x0,x1) => { x0.timeout = x1 },
      _2744: (x0,x1) => { x0.withCredentials = x1 },
      _2745: x0 => x0.upload,
      _2746: x0 => x0.responseURL,
      _2747: x0 => x0.status,
      _2748: x0 => x0.statusText,
      _2750: (x0,x1) => { x0.responseType = x1 },
      _2751: x0 => x0.response,
      _2763: x0 => x0.loaded,
      _2764: x0 => x0.total,
      _2811: (x0,x1) => { x0.draggable = x1 },
      _2827: x0 => x0.style,
      _2840: (x0,x1) => { x0.oncancel = x1 },
      _2846: (x0,x1) => { x0.onchange = x1 },
      _2886: (x0,x1) => { x0.onerror = x1 },
      _3026: (x0,x1) => { x0.nonce = x1 },
      _3080: x0 => x0.content,
      _3186: (x0,x1) => { x0.download = x1 },
      _3211: (x0,x1) => { x0.href = x1 },
      _3259: (x0,x1) => { x0.src = x1 },
      _3304: (x0,x1) => { x0.src = x1 },
      _3753: (x0,x1) => { x0.accept = x1 },
      _3767: x0 => x0.files,
      _3793: (x0,x1) => { x0.multiple = x1 },
      _3811: (x0,x1) => { x0.type = x1 },
      _4061: (x0,x1) => { x0.src = x1 },
      _4063: (x0,x1) => { x0.type = x1 },
      _4067: (x0,x1) => { x0.async = x1 },
      _4069: (x0,x1) => { x0.defer = x1 },
      _4081: (x0,x1) => { x0.charset = x1 },
      _4106: (x0,x1) => { x0.width = x1 },
      _4108: (x0,x1) => { x0.height = x1 },
      _4528: () => globalThis.window,
      _4568: x0 => x0.document,
      _4571: x0 => x0.location,
      _4590: x0 => x0.navigator,
      _4845: x0 => x0.isSecureContext,
      _4848: x0 => x0.crypto,
      _4852: x0 => x0.trustedTypes,
      _4853: x0 => x0.sessionStorage,
      _4854: x0 => x0.localStorage,
      _4862: x0 => x0.href,
      _4913: x0 => x0.message,
      _4955: x0 => x0.clipboard,
      _4957: x0 => x0.geolocation,
      _4960: x0 => x0.mediaDevices,
      _4962: x0 => x0.permissions,
      _4963: x0 => x0.maxTouchPoints,
      _4970: x0 => x0.appCodeName,
      _4971: x0 => x0.appName,
      _4972: x0 => x0.appVersion,
      _4973: x0 => x0.platform,
      _4974: x0 => x0.product,
      _4975: x0 => x0.productSub,
      _4976: x0 => x0.userAgent,
      _4977: x0 => x0.vendor,
      _4978: x0 => x0.vendorSub,
      _4980: x0 => x0.language,
      _4981: x0 => x0.languages,
      _4982: x0 => x0.onLine,
      _4987: x0 => x0.hardwareConcurrency,
      _4989: x0 => x0.storage,
      _5009: x0 => x0.width,
      _5010: x0 => x0.height,
      _5026: x0 => x0.data,
      _5027: x0 => x0.origin,
      _5056: x0 => x0.port1,
      _5057: x0 => x0.port2,
      _5059: (x0,x1) => { x0.onmessage = x1 },
      _5137: x0 => x0.port,
      _5172: x0 => x0.length,
      _7072: x0 => x0.type,
      _7073: x0 => x0.target,
      _7113: x0 => x0.signal,
      _7122: x0 => x0.length,
      _7164: x0 => x0.baseURI,
      _7170: x0 => x0.firstChild,
      _7181: () => globalThis.document,
      _7262: x0 => x0.body,
      _7264: x0 => x0.head,
      _7592: (x0,x1) => { x0.id = x1 },
      _7619: x0 => x0.children,
      _8938: x0 => x0.value,
      _8940: x0 => x0.done,
      _9099: x0 => x0.size,
      _9100: x0 => x0.type,
      _9103: (x0,x1) => { x0.type = x1 },
      _9106: x0 => x0.name,
      _9107: x0 => x0.lastModified,
      _9112: x0 => x0.length,
      _9117: x0 => x0.result,
      _9613: x0 => x0.url,
      _9615: x0 => x0.status,
      _9617: x0 => x0.statusText,
      _9618: x0 => x0.headers,
      _9619: x0 => x0.body,
      _11066: x0 => x0.result,
      _11067: x0 => x0.error,
      _11078: (x0,x1) => { x0.onupgradeneeded = x1 },
      _11080: x0 => x0.oldVersion,
      _11159: x0 => x0.key,
      _11160: x0 => x0.primaryKey,
      _11162: x0 => x0.value,
      _12000: (x0,x1) => { x0.display = x1 },
      _12164: (x0,x1) => { x0.height = x1 },
      _12336: (x0,x1) => { x0.maxWidth = x1 },
      _12854: (x0,x1) => { x0.width = x1 },
      _13222: x0 => x0.name,
      _13223: x0 => x0.message,
      _13226: x0 => x0.subtle,
      _13930: () => globalThis.console,
      _13958: () => globalThis.speechSynthesis,
      _13959: (x0,x1) => { x0.lang = x1 },
      _13961: (x0,x1) => { x0.pitch = x1 },
      _13964: (x0,x1) => { x0.rate = x1 },
      _13966: (x0,x1) => { x0.text = x1 },
      _13967: (x0,x1) => { x0.voice = x1 },
      _13968: x0 => x0.voice,
      _13970: (x0,x1) => { x0.volume = x1 },
      _13971: (x0,x1) => { x0.onstart = x1 },
      _13972: (x0,x1) => { x0.onend = x1 },
      _13973: (x0,x1) => { x0.onpause = x1 },
      _13974: (x0,x1) => { x0.onresume = x1 },
      _13975: (x0,x1) => { x0.onerror = x1 },
      _13976: (x0,x1) => { x0.onboundary = x1 },
      _13978: x0 => x0.lang,
      _13979: x0 => x0.localService,
      _13980: x0 => x0.name,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      s: [
        "([ \r\n\t]+)|([!-\\[\\]-‧‪-퟿豈-￿][̀-ͯ]*|[\ud800-\udbff][\udc00-\udfff][̀-ͯ]*|\\\\verb\\*([^]).*?\\3|\\\\verb([^*a-zA-Z]).*?\\4|\\\\operatorname\\*|\\\\[a-zA-Z@]+[ \r\n\t]*|\\\\[^\ud800-\udfff])",
      ],
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
